/*********************************************
 * sh4opcode.h
 *
 * Header file with all the LUT definitions
 *
 * @author Roberto Cano <roberto dot cano at google mail>
 *
 * THIS FILE IS AUTOMATICALLY GENERATED.
 * DO NOT MODIFY!!!!
 *
 *********************************************/
#ifndef __SH4OPCODE_H__
#define __SH4OPCODE_H__

#include <stdint.h>

/* SH4 opcode processor type */
typedef void (*SH4OPProcesor_t)(uint16_t);

/* Forward declaration of all opcode interpreter processors */
void __0000000000000000(uint16_t op); /**< EXCEPTION */
void __1110nnnniiiiiiii(uint16_t op); /**< mov     #i,rn */
void __1001nnnndddddddd(uint16_t op); /**< mov.w   @(d,pc),rn */
void __1101nnnndddddddd(uint16_t op); /**< mov.l   @(d,pc),rn */
void __0110nnnnmmmm0011(uint16_t op); /**< mov     rm,rn */
void __0010nnnnmmmm0000(uint16_t op); /**< mov.b   rm,@rn */
void __0010nnnnmmmm0001(uint16_t op); /**< mov.w   rm,@rn */
void __0010nnnnmmmm0010(uint16_t op); /**< mov.l   rm,@rn */
void __0110nnnnmmmm0000(uint16_t op); /**< mov.b   @rm,rn */
void __0110nnnnmmmm0001(uint16_t op); /**< mov.w   @rm,rn */
void __0110nnnnmmmm0010(uint16_t op); /**< mov.l   @rm,rn */
void __0010nnnnmmmm0100(uint16_t op); /**< mov.b   rm,@-rn */
void __0010nnnnmmmm0101(uint16_t op); /**< mov.w   rm,@-rn */
void __0010nnnnmmmm0110(uint16_t op); /**< mov.l   rm,@-rn */
void __0110nnnnmmmm0100(uint16_t op); /**< mov.b   @rm+,rn */
void __0110nnnnmmmm0101(uint16_t op); /**< mov.w   @rm+,rn */
void __0110nnnnmmmm0110(uint16_t op); /**< mov.l   @rm+,rn */
void __10000000nnnndddd(uint16_t op); /**< mov.b   r0,@(d,rn) */
void __10000001nnnndddd(uint16_t op); /**< mov.w   r0,@(d,rn) */
void __0001nnnnmmmmdddd(uint16_t op); /**< mov.l   rm,@(d,rn) */
void __10000100mmmmdddd(uint16_t op); /**< mov.b   @(d,rm),r0 */
void __10000101mmmmdddd(uint16_t op); /**< mov.w   @(d,rm),r0 */
void __0101nnnnmmmmdddd(uint16_t op); /**< mov.l   @(d,rm),rn */
void __0000nnnnmmmm0100(uint16_t op); /**< mov.b   rm,@(r0,rn) */
void __0000nnnnmmmm0101(uint16_t op); /**< mov.w   rm,@(r0,rn) */
void __0000nnnnmmmm0110(uint16_t op); /**< mov.l   rm,@(r0,rn) */
void __0000nnnnmmmm1100(uint16_t op); /**< mov.b   @(r0,rm),rn */
void __0000nnnnmmmm1101(uint16_t op); /**< mov.w   @(r0,rm),rn */
void __0000nnnnmmmm1110(uint16_t op); /**< mov.l   @(r0,rm),rn */
void __11000000dddddddd(uint16_t op); /**< mov.b   r0,@(d,gbr) */
void __11000001dddddddd(uint16_t op); /**< mov.w   r0,@(d,gbr) */
void __11000010dddddddd(uint16_t op); /**< mov.l   r0,@(d,gbr) */
void __11000100dddddddd(uint16_t op); /**< mov.b   @(d,gbr),r0 */
void __11000101dddddddd(uint16_t op); /**< mov.w   @(d,gbr),r0 */
void __11000110dddddddd(uint16_t op); /**< mov.l   @(d,gbr),r0 */
void __11000111dddddddd(uint16_t op); /**< mova    @(d,pc),r0 */
void __0000nnnn00101001(uint16_t op); /**< movt    rn */
void __0110nnnnmmmm1000(uint16_t op); /**< swap.b  rm,rn */
void __0110nnnnmmmm1001(uint16_t op); /**< swap.w  rm,rn */
void __0010nnnnmmmm1101(uint16_t op); /**< xtrct   rm,rn */
void __0011nnnnmmmm1100(uint16_t op); /**< add     rm,rn */
void __0111nnnniiiiiiii(uint16_t op); /**< add     #i,rn */
void __0011nnnnmmmm1110(uint16_t op); /**< addc    rm,rn */
void __0011nnnnmmmm1111(uint16_t op); /**< addv    rm,rn */
void __10001000iiiiiiii(uint16_t op); /**< cmp/eq  #i,r0 */
void __0011nnnnmmmm0000(uint16_t op); /**< cmp/eq  rm,rn */
void __0011nnnnmmmm0010(uint16_t op); /**< cmp/hs  rm,rn */
void __0011nnnnmmmm0011(uint16_t op); /**< cmp/ge  rm,rn */
void __0011nnnnmmmm0110(uint16_t op); /**< cmp/hi  rm,rn */
void __0011nnnnmmmm0111(uint16_t op); /**< cmp/gt  rm,rn */
void __0100nnnn00010001(uint16_t op); /**< cmp/pz  rn */
void __0100nnnn00010101(uint16_t op); /**< cmp/pl  rn */
void __0010nnnnmmmm1100(uint16_t op); /**< cmp/str rm,rn */
void __0011nnnnmmmm0100(uint16_t op); /**< div1    rm,rn */
void __0010nnnnmmmm0111(uint16_t op); /**< div0s   rm,rn */
void __0000000000011001(uint16_t op); /**< div0u */
void __0011nnnnmmmm1101(uint16_t op); /**< dmuls.l rm,rn */
void __0011nnnnmmmm0101(uint16_t op); /**< dmulu.l rm,rn */
void __0100nnnn00010000(uint16_t op); /**< dt      rn */
void __0110nnnnmmmm1110(uint16_t op); /**< exts.b  rm,rn */
void __0110nnnnmmmm1111(uint16_t op); /**< exts.w  rm,rn */
void __0110nnnnmmmm1100(uint16_t op); /**< extu.b  rm,rn */
void __0110nnnnmmmm1101(uint16_t op); /**< extu.w  rm,rn */
void __0000nnnnmmmm1111(uint16_t op); /**< mac.l   @rm+,@rn+ */
void __0100nnnnmmmm1111(uint16_t op); /**< mac.w   @rm+,@rn+ */
void __0000nnnnmmmm0111(uint16_t op); /**< mul.l   rm,rn */
void __0010nnnnmmmm1111(uint16_t op); /**< muls.w  rm,rn */
void __0010nnnnmmmm1110(uint16_t op); /**< mulu.w  rm,rn */
void __0110nnnnmmmm1011(uint16_t op); /**< neg     rm,rn */
void __0110nnnnmmmm1010(uint16_t op); /**< negc    rm,rn */
void __0011nnnnmmmm1000(uint16_t op); /**< sub     rm,rn */
void __0011nnnnmmmm1010(uint16_t op); /**< subc    rm,rn */
void __0011nnnnmmmm1011(uint16_t op); /**< subv    rm,rn */
void __0010nnnnmmmm1001(uint16_t op); /**< and     rm,rn */
void __11001001iiiiiiii(uint16_t op); /**< and     #i,r0 */
void __11001101iiiiiiii(uint16_t op); /**< and.b   #i,@(r0,gbr) */
void __0110nnnnmmmm0111(uint16_t op); /**< not     rm,rn */
void __0010nnnnmmmm1011(uint16_t op); /**< or      rm,rn */
void __11001011iiiiiiii(uint16_t op); /**< or      #i,r0 */
void __11001111iiiiiiii(uint16_t op); /**< or.b    #i,@(r0,gbr) */
void __0100nnnn00011011(uint16_t op); /**< tas.b   @rn */
void __0010nnnnmmmm1000(uint16_t op); /**< tst     rm,rn */
void __11001000iiiiiiii(uint16_t op); /**< tst     #i,r0 */
void __11001100iiiiiiii(uint16_t op); /**< tst.b   #i,@(r0,gbr) */
void __0010nnnnmmmm1010(uint16_t op); /**< xor     rm,rn */
void __11001010iiiiiiii(uint16_t op); /**< xor     #i,r0 */
void __11001110iiiiiiii(uint16_t op); /**< xor.b   #i,@(r0,gbr) */
void __0100nnnn00000100(uint16_t op); /**< rotl    rn */
void __0100nnnn00000101(uint16_t op); /**< rotr    rn */
void __0100nnnn00100100(uint16_t op); /**< rotcl   rn */
void __0100nnnn00100101(uint16_t op); /**< rotcr   rn */
void __0100nnnnmmmm1100(uint16_t op); /**< shad    rm,rn */
void __0100nnnn00100000(uint16_t op); /**< shal    rn */
void __0100nnnn00100001(uint16_t op); /**< shar    rn */
void __0100nnnnmmmm1101(uint16_t op); /**< shld    rm,rn */
void __0100nnnn00000000(uint16_t op); /**< shll    rn */
void __0100nnnn00000001(uint16_t op); /**< shlr    rn */
void __0100nnnn00001000(uint16_t op); /**< shll2   rn */
void __0100nnnn00001001(uint16_t op); /**< shlr2   rn */
void __0100nnnn00011000(uint16_t op); /**< shll8   rn */
void __0100nnnn00011001(uint16_t op); /**< shlr8   rn */
void __0100nnnn00101000(uint16_t op); /**< shll16  rn */
void __0100nnnn00101001(uint16_t op); /**< shlr16  rn */
void __10001011dddddddd(uint16_t op); /**< bf      d */
void __10001111dddddddd(uint16_t op); /**< bf/s    d */
void __10001001dddddddd(uint16_t op); /**< bt      d */
void __10001101dddddddd(uint16_t op); /**< bt/s    d */
void __1010dddddddddddd(uint16_t op); /**< bra     d */
void __0000nnnn00100011(uint16_t op); /**< braf    rn */
void __1011dddddddddddd(uint16_t op); /**< bsr     d */
void __0000nnnn00000011(uint16_t op); /**< bsrf    rn */
void __0100nnnn00101011(uint16_t op); /**< jmp     @rn */
void __0100nnnn00001011(uint16_t op); /**< jsr     @rn */
void __0000000000001011(uint16_t op); /**< rts */
void __0000000000101000(uint16_t op); /**< clrmac */
void __0000000001001000(uint16_t op); /**< clrs */
void __0000000000001000(uint16_t op); /**< clrt */
void __0100mmmm00001110(uint16_t op); /**< ldc     rm,sr */
void __0100mmmm00011110(uint16_t op); /**< ldc     rm,gbr */
void __0100mmmm00101110(uint16_t op); /**< ldc     rm,vbr */
void __0100mmmm00111110(uint16_t op); /**< ldc     rm,ssr */
void __0100mmmm01001110(uint16_t op); /**< ldc     rm,spc */
void __0100mmmm11111010(uint16_t op); /**< ldc     rm,dbr */
void __0100mmmm1nnn1110(uint16_t op); /**< ldc     rm,rn_bank */
void __0100mmmm00000111(uint16_t op); /**< ldc.l   @rm+,sr */
void __0100mmmm00010111(uint16_t op); /**< ldc.l   @rm+,gbr */
void __0100mmmm00100111(uint16_t op); /**< ldc.l   @rm+,vbr */
void __0100mmmm00110111(uint16_t op); /**< ldc.l   @rm+,ssr */
void __0100mmmm01000111(uint16_t op); /**< ldc.l   @rm+,spc */
void __0100mmmm11110110(uint16_t op); /**< ldc.l   @rm+,dbr */
void __0100mmmm1nnn0111(uint16_t op); /**< ldc.l   @rm+,rn_bank */
void __0100mmmm00001010(uint16_t op); /**< lds     rm,mach */
void __0100mmmm00011010(uint16_t op); /**< lds     rm,macl */
void __0100mmmm00101010(uint16_t op); /**< lds     rm,pr */
void __0100mmmm00000110(uint16_t op); /**< lds.l   @rm+,mach */
void __0100mmmm00010110(uint16_t op); /**< lds.l   @rm+,macl */
void __0100mmmm00100110(uint16_t op); /**< lds.l   @rm+,pr */
void __0000000000111000(uint16_t op); /**< ldtlb */
void __0000nnnn11000011(uint16_t op); /**< movca.l r0,@rn */
void __0000000000001001(uint16_t op); /**< nop */
void __0000nnnn10010011(uint16_t op); /**< ocbi    @rn */
void __0000nnnn10100011(uint16_t op); /**< ocbp    @rn */
void __0000nnnn10110011(uint16_t op); /**< ocbwb   @rn */
void __0000nnnn10000011(uint16_t op); /**< pref    @rn */
void __0000000000101011(uint16_t op); /**< rte */
void __0000000001011000(uint16_t op); /**< sets */
void __0000000000011000(uint16_t op); /**< sett */
void __0000000000011011(uint16_t op); /**< sleep */
void __0000nnnn00000010(uint16_t op); /**< stc     sr,rn */
void __0000nnnn00010010(uint16_t op); /**< stc     gbr,rn */
void __0000nnnn00100010(uint16_t op); /**< stc     vbr,rn */
void __0000nnnn00110010(uint16_t op); /**< stc     ssr,rn */
void __0000nnnn01000010(uint16_t op); /**< stc     spc,rn */
void __0000nnnn00111010(uint16_t op); /**< stc     sgr,rn */
void __0000nnnn11111010(uint16_t op); /**< stc     dbr,rn */
void __0000nnnn1mmm0010(uint16_t op); /**< stc     rm_bank,rn */
void __0100nnnn00000011(uint16_t op); /**< stc.l   sr,@-rn */
void __0100nnnn00010011(uint16_t op); /**< stc.l   gbr,@-rn */
void __0100nnnn00100011(uint16_t op); /**< stc.l   vbr,@-rn */
void __0100nnnn00110011(uint16_t op); /**< stc.l   ssr,@-rn */
void __0100nnnn01000011(uint16_t op); /**< stc.l   spc,@-rn */
void __0100nnnn00110010(uint16_t op); /**< stc.l   sgr,@-rn */
void __0100nnnn11110010(uint16_t op); /**< stc.l   dbr,@-rn */
void __0100nnnn1mmm0011(uint16_t op); /**< stc.l   rm_bank,@-rn */
void __0000nnnn00001010(uint16_t op); /**< sts     mach,rn */
void __0000nnnn00011010(uint16_t op); /**< sts     macl,rn */
void __0000nnnn00101010(uint16_t op); /**< sts   pr,rn */
void __0100nnnn00000010(uint16_t op); /**< sts.l   mach,@-rn */
void __0100nnnn00010010(uint16_t op); /**< sts.l   macl,@-rn */
void __0100nnnn00100010(uint16_t op); /**< sts.l   pr,@-rn */
void __11000011iiiiiiii(uint16_t op); /**< trapa   #i */
void __1111nnnn10001101(uint16_t op); /**< fldi0   frn */
void __1111nnnn10011101(uint16_t op); /**< fldi1   frn */
void __1111nnnnmmmm1100(uint16_t op); /**< fmov    frm,frn */
void __1111nnnnmmmm1000(uint16_t op); /**< fmov.s  @rm,frn */
void __1111nnnnmmmm0110(uint16_t op); /**< fmov.s  @(r0,rm),frn */
void __1111nnnnmmmm1001(uint16_t op); /**< fmov.s  @rm+,frn */
void __1111nnnnmmmm1010(uint16_t op); /**< fmov.s  frm,@rn */
void __1111nnnnmmmm1011(uint16_t op); /**< fmov.s  frm,@-rn */
void __1111nnnnmmmm0111(uint16_t op); /**< fmov.s  frm,@(r0,rn) */
void __1111nnn0mmm01100(uint16_t op); /**< fmov    drm,drn */
void __1111nnn0mmmm1000(uint16_t op); /**< fmov    @rm,drn */
void __1111nnn0mmmm0110(uint16_t op); /**< fmov    @(r0,rm),drn */
void __1111nnn0mmmm1001(uint16_t op); /**< fmov    @rm+,drn */
void __1111nnnnmmm01010(uint16_t op); /**< fmov    drm,@rn */
void __1111nnnnmmm01011(uint16_t op); /**< fmov    drm,@-rn */
void __1111nnnnmmm00111(uint16_t op); /**< fmov    drm,@(r0,rn) */
void __1111mmmm00011101(uint16_t op); /**< flds    frm,fpul */
void __1111nnnn00001101(uint16_t op); /**< fsts    fpul,frn */
void __1111nnnn01011101(uint16_t op); /**< fabs    frn */
void __1111nnnnmmmm0000(uint16_t op); /**< fadd    frm,frn */
void __1111nnnnmmmm0100(uint16_t op); /**< fcmp/eq frm,frn */
void __1111nnnnmmmm0101(uint16_t op); /**< fcmp/gt frm,frn */
void __1111nnnnmmmm0011(uint16_t op); /**< fdiv    frm,frn */
void __1111nnnn00101101(uint16_t op); /**< float   fpul,frn */
void __1111nnnnmmmm1110(uint16_t op); /**< fmac    fr0,frm,frn */
void __1111nnnnmmmm0010(uint16_t op); /**< fmul    frm,frn */
void __1111nnnn01001101(uint16_t op); /**< fneg    frn */
void __1111nnnn01101101(uint16_t op); /**< fsqrt   frn */
void __1111nnnnmmmm0001(uint16_t op); /**< fsub    frm,frn */
void __1111mmmm00111101(uint16_t op); /**< ftrc    frm,fpul */
void __1111nnn001011101(uint16_t op); /**< fabs    drn */
void __1111nnn0mmm00000(uint16_t op); /**< fadd    drm,drn */
void __1111nnn0mmm00100(uint16_t op); /**< fcmp/eq drm,drn */
void __1111nnn0mmm00101(uint16_t op); /**< fcmp/gt drm,drn */
void __1111nnn0mmm00011(uint16_t op); /**< fdiv    drm,drn */
void __1111mmm010111101(uint16_t op); /**< fcnvds  drm,fpul */
void __1111nnn010101101(uint16_t op); /**< fcnvsd  fpul,drn */
void __1111nnn000101101(uint16_t op); /**< float   fpul,drn */
void __1111nnn0mmm00010(uint16_t op); /**< fmul    drm,drn */
void __1111nnn001001101(uint16_t op); /**< fneg    drn */
void __1111nnn001101101(uint16_t op); /**< fsqrt   drn */
void __1111nnn0mmm00001(uint16_t op); /**< fsub    drm,drn */
void __1111mmm000111101(uint16_t op); /**< ftrc    drm,fpul */
void __0100mmmm01101010(uint16_t op); /**< lds     rm,fpscr */
void __0100mmmm01011010(uint16_t op); /**< lds     rm,fpul */
void __0100mmmm01100110(uint16_t op); /**< lds.l   @rm+,fpscr */
void __0100mmmm01010110(uint16_t op); /**< lds.l   @rm+,fpul */
void __0000nnnn01101010(uint16_t op); /**< sts     fpscr,rn */
void __0000nnnn01011010(uint16_t op); /**< sts     fpul,rn */
void __0100nnnn01100010(uint16_t op); /**< sts.l   fpscr,@-rn */
void __0100nnnn01010010(uint16_t op); /**< sts.l   fpul,@-rn */
void __1111nnn1mmm01100(uint16_t op); /**< fmov    drm,xdn */
void __1111nnn0mmm11100(uint16_t op); /**< fmov    xdm,drn */
void __1111nnn1mmm11100(uint16_t op); /**< fmov    xdm,xdn */
void __1111nnn1mmmm1000(uint16_t op); /**< fmov    @rm,xdn */
void __1111nnn1mmmm1001(uint16_t op); /**< fmov    @rm+,xdn */
void __1111nnn1mmmm0110(uint16_t op); /**< fmov    @(r0,rm),drn */
void __1111nnnnmmm11010(uint16_t op); /**< fmov    xdm,@rn */
void __1111nnnnmmm11011(uint16_t op); /**< fmov    xdm,@-rn */
void __1111nnnnmmm10111(uint16_t op); /**< fmov    xdm,@(r0,rn) */
void __1111nnmm11101101(uint16_t op); /**< fipr    fvm,fvn */
void __1111nn0111111101(uint16_t op); /**< ftrv    xmtrx,fvn */
void __1111101111111101(uint16_t op); /**< frchg */
void __1111001111111101(uint16_t op); /**< fschg */

/* Opcodes interpreter lookup table declaration */
extern SH4OPProcesor_t SH7750InterpLUT[];

/* Forward declaration of all opcode disasembler processors */
void __0000000000000000_dis(uint16_t op); /**< EXCEPTION */
void __1110nnnniiiiiiii_dis(uint16_t op); /**< mov     #i,rn */
void __1001nnnndddddddd_dis(uint16_t op); /**< mov.w   @(d,pc),rn */
void __1101nnnndddddddd_dis(uint16_t op); /**< mov.l   @(d,pc),rn */
void __0110nnnnmmmm0011_dis(uint16_t op); /**< mov     rm,rn */
void __0010nnnnmmmm0000_dis(uint16_t op); /**< mov.b   rm,@rn */
void __0010nnnnmmmm0001_dis(uint16_t op); /**< mov.w   rm,@rn */
void __0010nnnnmmmm0010_dis(uint16_t op); /**< mov.l   rm,@rn */
void __0110nnnnmmmm0000_dis(uint16_t op); /**< mov.b   @rm,rn */
void __0110nnnnmmmm0001_dis(uint16_t op); /**< mov.w   @rm,rn */
void __0110nnnnmmmm0010_dis(uint16_t op); /**< mov.l   @rm,rn */
void __0010nnnnmmmm0100_dis(uint16_t op); /**< mov.b   rm,@-rn */
void __0010nnnnmmmm0101_dis(uint16_t op); /**< mov.w   rm,@-rn */
void __0010nnnnmmmm0110_dis(uint16_t op); /**< mov.l   rm,@-rn */
void __0110nnnnmmmm0100_dis(uint16_t op); /**< mov.b   @rm+,rn */
void __0110nnnnmmmm0101_dis(uint16_t op); /**< mov.w   @rm+,rn */
void __0110nnnnmmmm0110_dis(uint16_t op); /**< mov.l   @rm+,rn */
void __10000000nnnndddd_dis(uint16_t op); /**< mov.b   r0,@(d,rn) */
void __10000001nnnndddd_dis(uint16_t op); /**< mov.w   r0,@(d,rn) */
void __0001nnnnmmmmdddd_dis(uint16_t op); /**< mov.l   rm,@(d,rn) */
void __10000100mmmmdddd_dis(uint16_t op); /**< mov.b   @(d,rm),r0 */
void __10000101mmmmdddd_dis(uint16_t op); /**< mov.w   @(d,rm),r0 */
void __0101nnnnmmmmdddd_dis(uint16_t op); /**< mov.l   @(d,rm),rn */
void __0000nnnnmmmm0100_dis(uint16_t op); /**< mov.b   rm,@(r0,rn) */
void __0000nnnnmmmm0101_dis(uint16_t op); /**< mov.w   rm,@(r0,rn) */
void __0000nnnnmmmm0110_dis(uint16_t op); /**< mov.l   rm,@(r0,rn) */
void __0000nnnnmmmm1100_dis(uint16_t op); /**< mov.b   @(r0,rm),rn */
void __0000nnnnmmmm1101_dis(uint16_t op); /**< mov.w   @(r0,rm),rn */
void __0000nnnnmmmm1110_dis(uint16_t op); /**< mov.l   @(r0,rm),rn */
void __11000000dddddddd_dis(uint16_t op); /**< mov.b   r0,@(d,gbr) */
void __11000001dddddddd_dis(uint16_t op); /**< mov.w   r0,@(d,gbr) */
void __11000010dddddddd_dis(uint16_t op); /**< mov.l   r0,@(d,gbr) */
void __11000100dddddddd_dis(uint16_t op); /**< mov.b   @(d,gbr),r0 */
void __11000101dddddddd_dis(uint16_t op); /**< mov.w   @(d,gbr),r0 */
void __11000110dddddddd_dis(uint16_t op); /**< mov.l   @(d,gbr),r0 */
void __11000111dddddddd_dis(uint16_t op); /**< mova    @(d,pc),r0 */
void __0000nnnn00101001_dis(uint16_t op); /**< movt    rn */
void __0110nnnnmmmm1000_dis(uint16_t op); /**< swap.b  rm,rn */
void __0110nnnnmmmm1001_dis(uint16_t op); /**< swap.w  rm,rn */
void __0010nnnnmmmm1101_dis(uint16_t op); /**< xtrct   rm,rn */
void __0011nnnnmmmm1100_dis(uint16_t op); /**< add     rm,rn */
void __0111nnnniiiiiiii_dis(uint16_t op); /**< add     #i,rn */
void __0011nnnnmmmm1110_dis(uint16_t op); /**< addc    rm,rn */
void __0011nnnnmmmm1111_dis(uint16_t op); /**< addv    rm,rn */
void __10001000iiiiiiii_dis(uint16_t op); /**< cmp/eq  #i,r0 */
void __0011nnnnmmmm0000_dis(uint16_t op); /**< cmp/eq  rm,rn */
void __0011nnnnmmmm0010_dis(uint16_t op); /**< cmp/hs  rm,rn */
void __0011nnnnmmmm0011_dis(uint16_t op); /**< cmp/ge  rm,rn */
void __0011nnnnmmmm0110_dis(uint16_t op); /**< cmp/hi  rm,rn */
void __0011nnnnmmmm0111_dis(uint16_t op); /**< cmp/gt  rm,rn */
void __0100nnnn00010001_dis(uint16_t op); /**< cmp/pz  rn */
void __0100nnnn00010101_dis(uint16_t op); /**< cmp/pl  rn */
void __0010nnnnmmmm1100_dis(uint16_t op); /**< cmp/str rm,rn */
void __0011nnnnmmmm0100_dis(uint16_t op); /**< div1    rm,rn */
void __0010nnnnmmmm0111_dis(uint16_t op); /**< div0s   rm,rn */
void __0000000000011001_dis(uint16_t op); /**< div0u */
void __0011nnnnmmmm1101_dis(uint16_t op); /**< dmuls.l rm,rn */
void __0011nnnnmmmm0101_dis(uint16_t op); /**< dmulu.l rm,rn */
void __0100nnnn00010000_dis(uint16_t op); /**< dt      rn */
void __0110nnnnmmmm1110_dis(uint16_t op); /**< exts.b  rm,rn */
void __0110nnnnmmmm1111_dis(uint16_t op); /**< exts.w  rm,rn */
void __0110nnnnmmmm1100_dis(uint16_t op); /**< extu.b  rm,rn */
void __0110nnnnmmmm1101_dis(uint16_t op); /**< extu.w  rm,rn */
void __0000nnnnmmmm1111_dis(uint16_t op); /**< mac.l   @rm+,@rn+ */
void __0100nnnnmmmm1111_dis(uint16_t op); /**< mac.w   @rm+,@rn+ */
void __0000nnnnmmmm0111_dis(uint16_t op); /**< mul.l   rm,rn */
void __0010nnnnmmmm1111_dis(uint16_t op); /**< muls.w  rm,rn */
void __0010nnnnmmmm1110_dis(uint16_t op); /**< mulu.w  rm,rn */
void __0110nnnnmmmm1011_dis(uint16_t op); /**< neg     rm,rn */
void __0110nnnnmmmm1010_dis(uint16_t op); /**< negc    rm,rn */
void __0011nnnnmmmm1000_dis(uint16_t op); /**< sub     rm,rn */
void __0011nnnnmmmm1010_dis(uint16_t op); /**< subc    rm,rn */
void __0011nnnnmmmm1011_dis(uint16_t op); /**< subv    rm,rn */
void __0010nnnnmmmm1001_dis(uint16_t op); /**< and     rm,rn */
void __11001001iiiiiiii_dis(uint16_t op); /**< and     #i,r0 */
void __11001101iiiiiiii_dis(uint16_t op); /**< and.b   #i,@(r0,gbr) */
void __0110nnnnmmmm0111_dis(uint16_t op); /**< not     rm,rn */
void __0010nnnnmmmm1011_dis(uint16_t op); /**< or      rm,rn */
void __11001011iiiiiiii_dis(uint16_t op); /**< or      #i,r0 */
void __11001111iiiiiiii_dis(uint16_t op); /**< or.b    #i,@(r0,gbr) */
void __0100nnnn00011011_dis(uint16_t op); /**< tas.b   @rn */
void __0010nnnnmmmm1000_dis(uint16_t op); /**< tst     rm,rn */
void __11001000iiiiiiii_dis(uint16_t op); /**< tst     #i,r0 */
void __11001100iiiiiiii_dis(uint16_t op); /**< tst.b   #i,@(r0,gbr) */
void __0010nnnnmmmm1010_dis(uint16_t op); /**< xor     rm,rn */
void __11001010iiiiiiii_dis(uint16_t op); /**< xor     #i,r0 */
void __11001110iiiiiiii_dis(uint16_t op); /**< xor.b   #i,@(r0,gbr) */
void __0100nnnn00000100_dis(uint16_t op); /**< rotl    rn */
void __0100nnnn00000101_dis(uint16_t op); /**< rotr    rn */
void __0100nnnn00100100_dis(uint16_t op); /**< rotcl   rn */
void __0100nnnn00100101_dis(uint16_t op); /**< rotcr   rn */
void __0100nnnnmmmm1100_dis(uint16_t op); /**< shad    rm,rn */
void __0100nnnn00100000_dis(uint16_t op); /**< shal    rn */
void __0100nnnn00100001_dis(uint16_t op); /**< shar    rn */
void __0100nnnnmmmm1101_dis(uint16_t op); /**< shld    rm,rn */
void __0100nnnn00000000_dis(uint16_t op); /**< shll    rn */
void __0100nnnn00000001_dis(uint16_t op); /**< shlr    rn */
void __0100nnnn00001000_dis(uint16_t op); /**< shll2   rn */
void __0100nnnn00001001_dis(uint16_t op); /**< shlr2   rn */
void __0100nnnn00011000_dis(uint16_t op); /**< shll8   rn */
void __0100nnnn00011001_dis(uint16_t op); /**< shlr8   rn */
void __0100nnnn00101000_dis(uint16_t op); /**< shll16  rn */
void __0100nnnn00101001_dis(uint16_t op); /**< shlr16  rn */
void __10001011dddddddd_dis(uint16_t op); /**< bf      d */
void __10001111dddddddd_dis(uint16_t op); /**< bf/s    d */
void __10001001dddddddd_dis(uint16_t op); /**< bt      d */
void __10001101dddddddd_dis(uint16_t op); /**< bt/s    d */
void __1010dddddddddddd_dis(uint16_t op); /**< bra     d */
void __0000nnnn00100011_dis(uint16_t op); /**< braf    rn */
void __1011dddddddddddd_dis(uint16_t op); /**< bsr     d */
void __0000nnnn00000011_dis(uint16_t op); /**< bsrf    rn */
void __0100nnnn00101011_dis(uint16_t op); /**< jmp     @rn */
void __0100nnnn00001011_dis(uint16_t op); /**< jsr     @rn */
void __0000000000001011_dis(uint16_t op); /**< rts */
void __0000000000101000_dis(uint16_t op); /**< clrmac */
void __0000000001001000_dis(uint16_t op); /**< clrs */
void __0000000000001000_dis(uint16_t op); /**< clrt */
void __0100mmmm00001110_dis(uint16_t op); /**< ldc     rm,sr */
void __0100mmmm00011110_dis(uint16_t op); /**< ldc     rm,gbr */
void __0100mmmm00101110_dis(uint16_t op); /**< ldc     rm,vbr */
void __0100mmmm00111110_dis(uint16_t op); /**< ldc     rm,ssr */
void __0100mmmm01001110_dis(uint16_t op); /**< ldc     rm,spc */
void __0100mmmm11111010_dis(uint16_t op); /**< ldc     rm,dbr */
void __0100mmmm1nnn1110_dis(uint16_t op); /**< ldc     rm,rn_bank */
void __0100mmmm00000111_dis(uint16_t op); /**< ldc.l   @rm+,sr */
void __0100mmmm00010111_dis(uint16_t op); /**< ldc.l   @rm+,gbr */
void __0100mmmm00100111_dis(uint16_t op); /**< ldc.l   @rm+,vbr */
void __0100mmmm00110111_dis(uint16_t op); /**< ldc.l   @rm+,ssr */
void __0100mmmm01000111_dis(uint16_t op); /**< ldc.l   @rm+,spc */
void __0100mmmm11110110_dis(uint16_t op); /**< ldc.l   @rm+,dbr */
void __0100mmmm1nnn0111_dis(uint16_t op); /**< ldc.l   @rm+,rn_bank */
void __0100mmmm00001010_dis(uint16_t op); /**< lds     rm,mach */
void __0100mmmm00011010_dis(uint16_t op); /**< lds     rm,macl */
void __0100mmmm00101010_dis(uint16_t op); /**< lds     rm,pr */
void __0100mmmm00000110_dis(uint16_t op); /**< lds.l   @rm+,mach */
void __0100mmmm00010110_dis(uint16_t op); /**< lds.l   @rm+,macl */
void __0100mmmm00100110_dis(uint16_t op); /**< lds.l   @rm+,pr */
void __0000000000111000_dis(uint16_t op); /**< ldtlb */
void __0000nnnn11000011_dis(uint16_t op); /**< movca.l r0,@rn */
void __0000000000001001_dis(uint16_t op); /**< nop */
void __0000nnnn10010011_dis(uint16_t op); /**< ocbi    @rn */
void __0000nnnn10100011_dis(uint16_t op); /**< ocbp    @rn */
void __0000nnnn10110011_dis(uint16_t op); /**< ocbwb   @rn */
void __0000nnnn10000011_dis(uint16_t op); /**< pref    @rn */
void __0000000000101011_dis(uint16_t op); /**< rte */
void __0000000001011000_dis(uint16_t op); /**< sets */
void __0000000000011000_dis(uint16_t op); /**< sett */
void __0000000000011011_dis(uint16_t op); /**< sleep */
void __0000nnnn00000010_dis(uint16_t op); /**< stc     sr,rn */
void __0000nnnn00010010_dis(uint16_t op); /**< stc     gbr,rn */
void __0000nnnn00100010_dis(uint16_t op); /**< stc     vbr,rn */
void __0000nnnn00110010_dis(uint16_t op); /**< stc     ssr,rn */
void __0000nnnn01000010_dis(uint16_t op); /**< stc     spc,rn */
void __0000nnnn00111010_dis(uint16_t op); /**< stc     sgr,rn */
void __0000nnnn11111010_dis(uint16_t op); /**< stc     dbr,rn */
void __0000nnnn1mmm0010_dis(uint16_t op); /**< stc     rm_bank,rn */
void __0100nnnn00000011_dis(uint16_t op); /**< stc.l   sr,@-rn */
void __0100nnnn00010011_dis(uint16_t op); /**< stc.l   gbr,@-rn */
void __0100nnnn00100011_dis(uint16_t op); /**< stc.l   vbr,@-rn */
void __0100nnnn00110011_dis(uint16_t op); /**< stc.l   ssr,@-rn */
void __0100nnnn01000011_dis(uint16_t op); /**< stc.l   spc,@-rn */
void __0100nnnn00110010_dis(uint16_t op); /**< stc.l   sgr,@-rn */
void __0100nnnn11110010_dis(uint16_t op); /**< stc.l   dbr,@-rn */
void __0100nnnn1mmm0011_dis(uint16_t op); /**< stc.l   rm_bank,@-rn */
void __0000nnnn00001010_dis(uint16_t op); /**< sts     mach,rn */
void __0000nnnn00011010_dis(uint16_t op); /**< sts     macl,rn */
void __0000nnnn00101010_dis(uint16_t op); /**< sts   pr,rn */
void __0100nnnn00000010_dis(uint16_t op); /**< sts.l   mach,@-rn */
void __0100nnnn00010010_dis(uint16_t op); /**< sts.l   macl,@-rn */
void __0100nnnn00100010_dis(uint16_t op); /**< sts.l   pr,@-rn */
void __11000011iiiiiiii_dis(uint16_t op); /**< trapa   #i */
void __1111nnnn10001101_dis(uint16_t op); /**< fldi0   frn */
void __1111nnnn10011101_dis(uint16_t op); /**< fldi1   frn */
void __1111nnnnmmmm1100_dis(uint16_t op); /**< fmov    frm,frn */
void __1111nnnnmmmm1000_dis(uint16_t op); /**< fmov.s  @rm,frn */
void __1111nnnnmmmm0110_dis(uint16_t op); /**< fmov.s  @(r0,rm),frn */
void __1111nnnnmmmm1001_dis(uint16_t op); /**< fmov.s  @rm+,frn */
void __1111nnnnmmmm1010_dis(uint16_t op); /**< fmov.s  frm,@rn */
void __1111nnnnmmmm1011_dis(uint16_t op); /**< fmov.s  frm,@-rn */
void __1111nnnnmmmm0111_dis(uint16_t op); /**< fmov.s  frm,@(r0,rn) */
void __1111nnn0mmm01100_dis(uint16_t op); /**< fmov    drm,drn */
void __1111nnn0mmmm1000_dis(uint16_t op); /**< fmov    @rm,drn */
void __1111nnn0mmmm0110_dis(uint16_t op); /**< fmov    @(r0,rm),drn */
void __1111nnn0mmmm1001_dis(uint16_t op); /**< fmov    @rm+,drn */
void __1111nnnnmmm01010_dis(uint16_t op); /**< fmov    drm,@rn */
void __1111nnnnmmm01011_dis(uint16_t op); /**< fmov    drm,@-rn */
void __1111nnnnmmm00111_dis(uint16_t op); /**< fmov    drm,@(r0,rn) */
void __1111mmmm00011101_dis(uint16_t op); /**< flds    frm,fpul */
void __1111nnnn00001101_dis(uint16_t op); /**< fsts    fpul,frn */
void __1111nnnn01011101_dis(uint16_t op); /**< fabs    frn */
void __1111nnnnmmmm0000_dis(uint16_t op); /**< fadd    frm,frn */
void __1111nnnnmmmm0100_dis(uint16_t op); /**< fcmp/eq frm,frn */
void __1111nnnnmmmm0101_dis(uint16_t op); /**< fcmp/gt frm,frn */
void __1111nnnnmmmm0011_dis(uint16_t op); /**< fdiv    frm,frn */
void __1111nnnn00101101_dis(uint16_t op); /**< float   fpul,frn */
void __1111nnnnmmmm1110_dis(uint16_t op); /**< fmac    fr0,frm,frn */
void __1111nnnnmmmm0010_dis(uint16_t op); /**< fmul    frm,frn */
void __1111nnnn01001101_dis(uint16_t op); /**< fneg    frn */
void __1111nnnn01101101_dis(uint16_t op); /**< fsqrt   frn */
void __1111nnnnmmmm0001_dis(uint16_t op); /**< fsub    frm,frn */
void __1111mmmm00111101_dis(uint16_t op); /**< ftrc    frm,fpul */
void __1111nnn001011101_dis(uint16_t op); /**< fabs    drn */
void __1111nnn0mmm00000_dis(uint16_t op); /**< fadd    drm,drn */
void __1111nnn0mmm00100_dis(uint16_t op); /**< fcmp/eq drm,drn */
void __1111nnn0mmm00101_dis(uint16_t op); /**< fcmp/gt drm,drn */
void __1111nnn0mmm00011_dis(uint16_t op); /**< fdiv    drm,drn */
void __1111mmm010111101_dis(uint16_t op); /**< fcnvds  drm,fpul */
void __1111nnn010101101_dis(uint16_t op); /**< fcnvsd  fpul,drn */
void __1111nnn000101101_dis(uint16_t op); /**< float   fpul,drn */
void __1111nnn0mmm00010_dis(uint16_t op); /**< fmul    drm,drn */
void __1111nnn001001101_dis(uint16_t op); /**< fneg    drn */
void __1111nnn001101101_dis(uint16_t op); /**< fsqrt   drn */
void __1111nnn0mmm00001_dis(uint16_t op); /**< fsub    drm,drn */
void __1111mmm000111101_dis(uint16_t op); /**< ftrc    drm,fpul */
void __0100mmmm01101010_dis(uint16_t op); /**< lds     rm,fpscr */
void __0100mmmm01011010_dis(uint16_t op); /**< lds     rm,fpul */
void __0100mmmm01100110_dis(uint16_t op); /**< lds.l   @rm+,fpscr */
void __0100mmmm01010110_dis(uint16_t op); /**< lds.l   @rm+,fpul */
void __0000nnnn01101010_dis(uint16_t op); /**< sts     fpscr,rn */
void __0000nnnn01011010_dis(uint16_t op); /**< sts     fpul,rn */
void __0100nnnn01100010_dis(uint16_t op); /**< sts.l   fpscr,@-rn */
void __0100nnnn01010010_dis(uint16_t op); /**< sts.l   fpul,@-rn */
void __1111nnn1mmm01100_dis(uint16_t op); /**< fmov    drm,xdn */
void __1111nnn0mmm11100_dis(uint16_t op); /**< fmov    xdm,drn */
void __1111nnn1mmm11100_dis(uint16_t op); /**< fmov    xdm,xdn */
void __1111nnn1mmmm1000_dis(uint16_t op); /**< fmov    @rm,xdn */
void __1111nnn1mmmm1001_dis(uint16_t op); /**< fmov    @rm+,xdn */
void __1111nnn1mmmm0110_dis(uint16_t op); /**< fmov    @(r0,rm),drn */
void __1111nnnnmmm11010_dis(uint16_t op); /**< fmov    xdm,@rn */
void __1111nnnnmmm11011_dis(uint16_t op); /**< fmov    xdm,@-rn */
void __1111nnnnmmm10111_dis(uint16_t op); /**< fmov    xdm,@(r0,rn) */
void __1111nnmm11101101_dis(uint16_t op); /**< fipr    fvm,fvn */
void __1111nn0111111101_dis(uint16_t op); /**< ftrv    xmtrx,fvn */
void __1111101111111101_dis(uint16_t op); /**< frchg */
void __1111001111111101_dis(uint16_t op); /**< fschg */

/* Opcodes disassembler lookup table declaration */
extern SH4OPProcesor_t SH7750DisasmLUT[];

#endif // __SH4OPCODE_H__
