/*********************************************
 * sh4opcodedis.c
 *
 * Contains the implementation of the processing functions for the disassembler
 *
 * @author Roberto Cano <roberto dot cano at google mail>
 *
 * THIS FILE IS AUTOMATICALLY GENERATED.
 * DO NOT MODIFY!!!!
 *
 *********************************************/
#include "sh4opcode.h"
#include <stdio.h>

#ifdef SH7750_ENABLE_DISASSEMBLER
void __0000000000000000_dis(uint16_t op)
{
    /* EXCEPTION */
    fprintf(stdout, "EXCEPTION\n");
}

void __1110nnnniiiiiiii_dis(uint16_t op)
{
    /* mov     #i,rn */
    int8_t n = (op>>8)&0xf;
    int8_t i = op&0xff;
    fprintf(stdout, "mov     #%d,r%d\n", i, n);
}

void __1001nnnndddddddd_dis(uint16_t op)
{
    /* mov.w   @(d,pc),rn */
    int8_t n = (op>>8)&0xf;
    int8_t d = op&0xff;
    fprintf(stdout, "mov.w   @(%d,pc),r%d\n", d, n);
}

void __1101nnnndddddddd_dis(uint16_t op)
{
    /* mov.l   @(d,pc),rn */
    int8_t n = (op>>8)&0xf;
    int8_t d = op&0xff;
    fprintf(stdout, "mov.l   @(%d,pc),r%d\n", d, n);
}

void __0110nnnnmmmm0011_dis(uint16_t op)
{
    /* mov     rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov     r%d,r%d\n", m, n);
}

void __0010nnnnmmmm0000_dis(uint16_t op)
{
    /* mov.b   rm,@rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.b   r%d,@r%d\n", m, n);
}

void __0010nnnnmmmm0001_dis(uint16_t op)
{
    /* mov.w   rm,@rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.w   r%d,@r%d\n", m, n);
}

void __0010nnnnmmmm0010_dis(uint16_t op)
{
    /* mov.l   rm,@rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.l   r%d,@r%d\n", m, n);
}

void __0110nnnnmmmm0000_dis(uint16_t op)
{
    /* mov.b   @rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.b   @r%d,r%d\n", m, n);
}

void __0110nnnnmmmm0001_dis(uint16_t op)
{
    /* mov.w   @rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.w   @r%d,r%d\n", m, n);
}

void __0110nnnnmmmm0010_dis(uint16_t op)
{
    /* mov.l   @rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.l   @r%d,r%d\n", m, n);
}

void __0010nnnnmmmm0100_dis(uint16_t op)
{
    /* mov.b   rm,@-rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.b   r%d,@-r%d\n", m, n);
}

void __0010nnnnmmmm0101_dis(uint16_t op)
{
    /* mov.w   rm,@-rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.w   r%d,@-r%d\n", m, n);
}

void __0010nnnnmmmm0110_dis(uint16_t op)
{
    /* mov.l   rm,@-rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.l   r%d,@-r%d\n", m, n);
}

void __0110nnnnmmmm0100_dis(uint16_t op)
{
    /* mov.b   @rm+,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.b   @r%d+,r%d\n", m, n);
}

void __0110nnnnmmmm0101_dis(uint16_t op)
{
    /* mov.w   @rm+,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.w   @r%d+,r%d\n", m, n);
}

void __0110nnnnmmmm0110_dis(uint16_t op)
{
    /* mov.l   @rm+,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.l   @r%d+,r%d\n", m, n);
}

void __10000000nnnndddd_dis(uint16_t op)
{
    /* mov.b   r0,@(d,rn) */
    int8_t n = (op>>4)&0xf;
    int8_t d = op&0xf;
    fprintf(stdout, "mov.b   r0,@(%d,r%d)\n", d, n);
}

void __10000001nnnndddd_dis(uint16_t op)
{
    /* mov.w   r0,@(d,rn) */
    int8_t n = (op>>4)&0xf;
    int8_t d = op&0xf;
    fprintf(stdout, "mov.w   r0,@(%d,r%d)\n", d, n);
}

void __0001nnnnmmmmdddd_dis(uint16_t op)
{
    /* mov.l   rm,@(d,rn) */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    int8_t d = op&0xf;
    fprintf(stdout, "mov.l   r%d,@(%d,r%d)\n", m, d, n);
}

void __10000100mmmmdddd_dis(uint16_t op)
{
    /* mov.b   @(d,rm),r0 */
    int8_t m = (op>>4)&0xf;
    int8_t d = op&0xf;
    fprintf(stdout, "mov.b   @(%d,r%d),r0\n", d, m);
}

void __10000101mmmmdddd_dis(uint16_t op)
{
    /* mov.w   @(d,rm),r0 */
    int8_t m = (op>>4)&0xf;
    int8_t d = op&0xf;
    fprintf(stdout, "mov.w   @(%d,r%d),r0\n", d, m);
}

void __0101nnnnmmmmdddd_dis(uint16_t op)
{
    /* mov.l   @(d,rm),rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    int8_t d = op&0xf;
    fprintf(stdout, "mov.l   @(%d,r%d),r%d\n", d, m, n);
}

void __0000nnnnmmmm0100_dis(uint16_t op)
{
    /* mov.b   rm,@(r0,rn) */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.b   r%d,@(r0,r%d)\n", m, n);
}

void __0000nnnnmmmm0101_dis(uint16_t op)
{
    /* mov.w   rm,@(r0,rn) */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.w   r%d,@(r0,r%d)\n", m, n);
}

void __0000nnnnmmmm0110_dis(uint16_t op)
{
    /* mov.l   rm,@(r0,rn) */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.l   r%d,@(r0,r%d)\n", m, n);
}

void __0000nnnnmmmm1100_dis(uint16_t op)
{
    /* mov.b   @(r0,rm),rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.b   @(r0,r%d),r%d\n", m, n);
}

void __0000nnnnmmmm1101_dis(uint16_t op)
{
    /* mov.w   @(r0,rm),rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.w   @(r0,r%d),r%d\n", m, n);
}

void __0000nnnnmmmm1110_dis(uint16_t op)
{
    /* mov.l   @(r0,rm),rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mov.l   @(r0,r%d),r%d\n", m, n);
}

void __11000000dddddddd_dis(uint16_t op)
{
    /* mov.b   r0,@(d,gbr) */
    int8_t d = op&0xff;
    fprintf(stdout, "mov.b   r0,@(%d,gbr)\n", d);
}

void __11000001dddddddd_dis(uint16_t op)
{
    /* mov.w   r0,@(d,gbr) */
    int8_t d = op&0xff;
    fprintf(stdout, "mov.w   r0,@(%d,gbr)\n", d);
}

void __11000010dddddddd_dis(uint16_t op)
{
    /* mov.l   r0,@(d,gbr) */
    int8_t d = op&0xff;
    fprintf(stdout, "mov.l   r0,@(%d,gbr)\n", d);
}

void __11000100dddddddd_dis(uint16_t op)
{
    /* mov.b   @(d,gbr),r0 */
    int8_t d = op&0xff;
    fprintf(stdout, "mov.b   @(%d,gbr),r0\n", d);
}

void __11000101dddddddd_dis(uint16_t op)
{
    /* mov.w   @(d,gbr),r0 */
    int8_t d = op&0xff;
    fprintf(stdout, "mov.w   @(%d,gbr),r0\n", d);
}

void __11000110dddddddd_dis(uint16_t op)
{
    /* mov.l   @(d,gbr),r0 */
    int8_t d = op&0xff;
    fprintf(stdout, "mov.l   @(%d,gbr),r0\n", d);
}

void __11000111dddddddd_dis(uint16_t op)
{
    /* mova    @(d,pc),r0 */
    int8_t d = op&0xff;
    fprintf(stdout, "mova    @(%d,pc),r0\n", d);
}

void __0000nnnn00101001_dis(uint16_t op)
{
    /* movt    rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "movt    r%d\n", n);
}

void __0110nnnnmmmm1000_dis(uint16_t op)
{
    /* swap.b  rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "swap.b  r%d,r%d\n", m, n);
}

void __0110nnnnmmmm1001_dis(uint16_t op)
{
    /* swap.w  rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "swap.w  r%d,r%d\n", m, n);
}

void __0010nnnnmmmm1101_dis(uint16_t op)
{
    /* xtrct   rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "xtrct   r%d,r%d\n", m, n);
}

void __0011nnnnmmmm1100_dis(uint16_t op)
{
    /* add     rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "add     r%d,r%d\n", m, n);
}

void __0111nnnniiiiiiii_dis(uint16_t op)
{
    /* add     #i,rn */
    int8_t n = (op>>8)&0xf;
    int8_t i = op&0xff;
    fprintf(stdout, "add     #%d,r%d\n", i, n);
}

void __0011nnnnmmmm1110_dis(uint16_t op)
{
    /* addc    rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "addc    r%d,r%d\n", m, n);
}

void __0011nnnnmmmm1111_dis(uint16_t op)
{
    /* addv    rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "addv    r%d,r%d\n", m, n);
}

void __10001000iiiiiiii_dis(uint16_t op)
{
    /* cmp/eq  #i,r0 */
    int8_t i = op&0xff;
    fprintf(stdout, "cmp/eq  #%d,r0\n", i);
}

void __0011nnnnmmmm0000_dis(uint16_t op)
{
    /* cmp/eq  rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "cmp/eq  r%d,r%d\n", m, n);
}

void __0011nnnnmmmm0010_dis(uint16_t op)
{
    /* cmp/hs  rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "cmp/hs  r%d,r%d\n", m, n);
}

void __0011nnnnmmmm0011_dis(uint16_t op)
{
    /* cmp/ge  rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "cmp/ge  r%d,r%d\n", m, n);
}

void __0011nnnnmmmm0110_dis(uint16_t op)
{
    /* cmp/hi  rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "cmp/hi  r%d,r%d\n", m, n);
}

void __0011nnnnmmmm0111_dis(uint16_t op)
{
    /* cmp/gt  rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "cmp/gt  r%d,r%d\n", m, n);
}

void __0100nnnn00010001_dis(uint16_t op)
{
    /* cmp/pz  rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "cmp/pz  r%d\n", n);
}

void __0100nnnn00010101_dis(uint16_t op)
{
    /* cmp/pl  rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "cmp/pl  r%d\n", n);
}

void __0010nnnnmmmm1100_dis(uint16_t op)
{
    /* cmp/str rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "cmp/str r%d,r%d\n", m, n);
}

void __0011nnnnmmmm0100_dis(uint16_t op)
{
    /* div1    rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "div1    r%d,r%d\n", m, n);
}

void __0010nnnnmmmm0111_dis(uint16_t op)
{
    /* div0s   rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "div0s   r%d,r%d\n", m, n);
}

void __0000000000011001_dis(uint16_t op)
{
    /* div0u */
    fprintf(stdout, "div0u\n");
}

void __0011nnnnmmmm1101_dis(uint16_t op)
{
    /* dmuls.l rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "dmuls.l r%d,r%d\n", m, n);
}

void __0011nnnnmmmm0101_dis(uint16_t op)
{
    /* dmulu.l rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "dmulu.l r%d,r%d\n", m, n);
}

void __0100nnnn00010000_dis(uint16_t op)
{
    /* dt      rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "dt      r%d\n", n);
}

void __0110nnnnmmmm1110_dis(uint16_t op)
{
    /* exts.b  rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "exts.b  r%d,r%d\n", m, n);
}

void __0110nnnnmmmm1111_dis(uint16_t op)
{
    /* exts.w  rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "exts.w  r%d,r%d\n", m, n);
}

void __0110nnnnmmmm1100_dis(uint16_t op)
{
    /* extu.b  rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "extu.b  r%d,r%d\n", m, n);
}

void __0110nnnnmmmm1101_dis(uint16_t op)
{
    /* extu.w  rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "extu.w  r%d,r%d\n", m, n);
}

void __0000nnnnmmmm1111_dis(uint16_t op)
{
    /* mac.l   @rm+,@rn+ */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mac.l   @r%d+,@r%d+\n", m, n);
}

void __0100nnnnmmmm1111_dis(uint16_t op)
{
    /* mac.w   @rm+,@rn+ */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mac.w   @r%d+,@r%d+\n", m, n);
}

void __0000nnnnmmmm0111_dis(uint16_t op)
{
    /* mul.l   rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mul.l   r%d,r%d\n", m, n);
}

void __0010nnnnmmmm1111_dis(uint16_t op)
{
    /* muls.w  rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "muls.w  r%d,r%d\n", m, n);
}

void __0010nnnnmmmm1110_dis(uint16_t op)
{
    /* mulu.w  rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "mulu.w  r%d,r%d\n", m, n);
}

void __0110nnnnmmmm1011_dis(uint16_t op)
{
    /* neg     rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "neg     r%d,r%d\n", m, n);
}

void __0110nnnnmmmm1010_dis(uint16_t op)
{
    /* negc    rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "negc    r%d,r%d\n", m, n);
}

void __0011nnnnmmmm1000_dis(uint16_t op)
{
    /* sub     rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "sub     r%d,r%d\n", m, n);
}

void __0011nnnnmmmm1010_dis(uint16_t op)
{
    /* subc    rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "subc    r%d,r%d\n", m, n);
}

void __0011nnnnmmmm1011_dis(uint16_t op)
{
    /* subv    rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "subv    r%d,r%d\n", m, n);
}

void __0010nnnnmmmm1001_dis(uint16_t op)
{
    /* and     rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "and     r%d,r%d\n", m, n);
}

void __11001001iiiiiiii_dis(uint16_t op)
{
    /* and     #i,r0 */
    int8_t i = op&0xff;
    fprintf(stdout, "and     #%d,r0\n", i);
}

void __11001101iiiiiiii_dis(uint16_t op)
{
    /* and.b   #i,@(r0,gbr) */
    int8_t i = op&0xff;
    fprintf(stdout, "and.b   #%d,@(r0,gbr)\n", i);
}

void __0110nnnnmmmm0111_dis(uint16_t op)
{
    /* not     rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "not     r%d,r%d\n", m, n);
}

void __0010nnnnmmmm1011_dis(uint16_t op)
{
    /* or      rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "or      r%d,r%d\n", m, n);
}

void __11001011iiiiiiii_dis(uint16_t op)
{
    /* or      #i,r0 */
    int8_t i = op&0xff;
    fprintf(stdout, "or      #%d,r0\n", i);
}

void __11001111iiiiiiii_dis(uint16_t op)
{
    /* or.b    #i,@(r0,gbr) */
    int8_t i = op&0xff;
    fprintf(stdout, "or.b    #%d,@(r0,gbr)\n", i);
}

void __0100nnnn00011011_dis(uint16_t op)
{
    /* tas.b   @rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "tas.b   @r%d\n", n);
}

void __0010nnnnmmmm1000_dis(uint16_t op)
{
    /* tst     rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "tst     r%d,r%d\n", m, n);
}

void __11001000iiiiiiii_dis(uint16_t op)
{
    /* tst     #i,r0 */
    int8_t i = op&0xff;
    fprintf(stdout, "tst     #%d,r0\n", i);
}

void __11001100iiiiiiii_dis(uint16_t op)
{
    /* tst.b   #i,@(r0,gbr) */
    int8_t i = op&0xff;
    fprintf(stdout, "tst.b   #%d,@(r0,gbr)\n", i);
}

void __0010nnnnmmmm1010_dis(uint16_t op)
{
    /* xor     rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "xor     r%d,r%d\n", m, n);
}

void __11001010iiiiiiii_dis(uint16_t op)
{
    /* xor     #i,r0 */
    int8_t i = op&0xff;
    fprintf(stdout, "xor     #%d,r0\n", i);
}

void __11001110iiiiiiii_dis(uint16_t op)
{
    /* xor.b   #i,@(r0,gbr) */
    int8_t i = op&0xff;
    fprintf(stdout, "xor.b   #%d,@(r0,gbr)\n", i);
}

void __0100nnnn00000100_dis(uint16_t op)
{
    /* rotl    rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "rotl    r%d\n", n);
}

void __0100nnnn00000101_dis(uint16_t op)
{
    /* rotr    rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "rotr    r%d\n", n);
}

void __0100nnnn00100100_dis(uint16_t op)
{
    /* rotcl   rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "rotcl   r%d\n", n);
}

void __0100nnnn00100101_dis(uint16_t op)
{
    /* rotcr   rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "rotcr   r%d\n", n);
}

void __0100nnnnmmmm1100_dis(uint16_t op)
{
    /* shad    rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "shad    r%d,r%d\n", m, n);
}

void __0100nnnn00100000_dis(uint16_t op)
{
    /* shal    rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "shal    r%d\n", n);
}

void __0100nnnn00100001_dis(uint16_t op)
{
    /* shar    rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "shar    r%d\n", n);
}

void __0100nnnnmmmm1101_dis(uint16_t op)
{
    /* shld    rm,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "shld    r%d,r%d\n", m, n);
}

void __0100nnnn00000000_dis(uint16_t op)
{
    /* shll    rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "shll    r%d\n", n);
}

void __0100nnnn00000001_dis(uint16_t op)
{
    /* shlr    rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "shlr    r%d\n", n);
}

void __0100nnnn00001000_dis(uint16_t op)
{
    /* shll2   rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "shll2   r%d\n", n);
}

void __0100nnnn00001001_dis(uint16_t op)
{
    /* shlr2   rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "shlr2   r%d\n", n);
}

void __0100nnnn00011000_dis(uint16_t op)
{
    /* shll8   rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "shll8   r%d\n", n);
}

void __0100nnnn00011001_dis(uint16_t op)
{
    /* shlr8   rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "shlr8   r%d\n", n);
}

void __0100nnnn00101000_dis(uint16_t op)
{
    /* shll16  rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "shll16  r%d\n", n);
}

void __0100nnnn00101001_dis(uint16_t op)
{
    /* shlr16  rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "shlr16  r%d\n", n);
}

void __10001011dddddddd_dis(uint16_t op)
{
    /* bf      d */
    int8_t d = op&0xff;
    fprintf(stdout, "bf      %d\n", d);
}

void __10001111dddddddd_dis(uint16_t op)
{
    /* bf/s    d */
    int8_t d = op&0xff;
    fprintf(stdout, "bf/s    %d\n", d);
}

void __10001001dddddddd_dis(uint16_t op)
{
    /* bt      d */
    int8_t d = op&0xff;
    fprintf(stdout, "bt      %d\n", d);
}

void __10001101dddddddd_dis(uint16_t op)
{
    /* bt/s    d */
    int8_t d = op&0xff;
    fprintf(stdout, "bt/s    %d\n", d);
}

void __1010dddddddddddd_dis(uint16_t op)
{
    /* bra     d */
    uint16_t d = op&0xfff;
    fprintf(stdout, "bra     %d\n", d);
}

void __0000nnnn00100011_dis(uint16_t op)
{
    /* braf    rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "braf    r%d\n", n);
}

void __1011dddddddddddd_dis(uint16_t op)
{
    /* bsr     d */
    uint16_t d = op&0xfff;
    fprintf(stdout, "bsr     %d\n", d);
}

void __0000nnnn00000011_dis(uint16_t op)
{
    /* bsrf    rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "bsrf    r%d\n", n);
}

void __0100nnnn00101011_dis(uint16_t op)
{
    /* jmp     @rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "jmp     @r%d\n", n);
}

void __0100nnnn00001011_dis(uint16_t op)
{
    /* jsr     @rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "jsr     @r%d\n", n);
}

void __0000000000001011_dis(uint16_t op)
{
    /* rts */
    fprintf(stdout, "rts\n");
}

void __0000000000101000_dis(uint16_t op)
{
    /* clrmac */
    fprintf(stdout, "clrmac\n");
}

void __0000000001001000_dis(uint16_t op)
{
    /* clrs */
    fprintf(stdout, "clrs\n");
}

void __0000000000001000_dis(uint16_t op)
{
    /* clrt */
    fprintf(stdout, "clrt\n");
}

void __0100mmmm00001110_dis(uint16_t op)
{
    /* ldc     rm,sr */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "ldc     r%d,sr\n", m);
}

void __0100mmmm00011110_dis(uint16_t op)
{
    /* ldc     rm,gbr */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "ldc     r%d,gbr\n", m);
}

void __0100mmmm00101110_dis(uint16_t op)
{
    /* ldc     rm,vbr */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "ldc     r%d,vbr\n", m);
}

void __0100mmmm00111110_dis(uint16_t op)
{
    /* ldc     rm,ssr */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "ldc     r%d,ssr\n", m);
}

void __0100mmmm01001110_dis(uint16_t op)
{
    /* ldc     rm,spc */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "ldc     r%d,spc\n", m);
}

void __0100mmmm11111010_dis(uint16_t op)
{
    /* ldc     rm,dbr */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "ldc     r%d,dbr\n", m);
}

void __0100mmmm1nnn1110_dis(uint16_t op)
{
    /* ldc     rm,rn_bank */
    int8_t m = (op>>8)&0xf;
    int8_t n = (op>>4)&0x7;
    fprintf(stdout, "ldc     r%d,r%d_bank\n", m, n);
}

void __0100mmmm00000111_dis(uint16_t op)
{
    /* ldc.l   @rm+,sr */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "ldc.l   @r%d+,sr\n", m);
}

void __0100mmmm00010111_dis(uint16_t op)
{
    /* ldc.l   @rm+,gbr */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "ldc.l   @r%d+,gbr\n", m);
}

void __0100mmmm00100111_dis(uint16_t op)
{
    /* ldc.l   @rm+,vbr */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "ldc.l   @r%d+,vbr\n", m);
}

void __0100mmmm00110111_dis(uint16_t op)
{
    /* ldc.l   @rm+,ssr */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "ldc.l   @r%d+,ssr\n", m);
}

void __0100mmmm01000111_dis(uint16_t op)
{
    /* ldc.l   @rm+,spc */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "ldc.l   @r%d+,spc\n", m);
}

void __0100mmmm11110110_dis(uint16_t op)
{
    /* ldc.l   @rm+,dbr */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "ldc.l   @r%d+,dbr\n", m);
}

void __0100mmmm1nnn0111_dis(uint16_t op)
{
    /* ldc.l   @rm+,rn_bank */
    int8_t m = (op>>8)&0xf;
    int8_t n = (op>>4)&0x7;
    fprintf(stdout, "ldc.l   @r%d+,r%d_bank\n", m, n);
}

void __0100mmmm00001010_dis(uint16_t op)
{
    /* lds     rm,mach */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "lds     r%d,mach\n", m);
}

void __0100mmmm00011010_dis(uint16_t op)
{
    /* lds     rm,macl */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "lds     r%d,macl\n", m);
}

void __0100mmmm00101010_dis(uint16_t op)
{
    /* lds     rm,pr */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "lds     r%d,pr\n", m);
}

void __0100mmmm00000110_dis(uint16_t op)
{
    /* lds.l   @rm+,mach */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "lds.l   @r%d+,mach\n", m);
}

void __0100mmmm00010110_dis(uint16_t op)
{
    /* lds.l   @rm+,macl */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "lds.l   @r%d+,macl\n", m);
}

void __0100mmmm00100110_dis(uint16_t op)
{
    /* lds.l   @rm+,pr */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "lds.l   @r%d+,pr\n", m);
}

void __0000000000111000_dis(uint16_t op)
{
    /* ldtlb */
    fprintf(stdout, "ldtlb\n");
}

void __0000nnnn11000011_dis(uint16_t op)
{
    /* movca.l r0,@rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "movca.l r0,@r%d\n", n);
}

void __0000000000001001_dis(uint16_t op)
{
    /* nop */
    fprintf(stdout, "nop\n");
}

void __0000nnnn10010011_dis(uint16_t op)
{
    /* ocbi    @rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "ocbi    @r%d\n", n);
}

void __0000nnnn10100011_dis(uint16_t op)
{
    /* ocbp    @rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "ocbp    @r%d\n", n);
}

void __0000nnnn10110011_dis(uint16_t op)
{
    /* ocbwb   @rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "ocbwb   @r%d\n", n);
}

void __0000nnnn10000011_dis(uint16_t op)
{
    /* pref    @rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "pref    @r%d\n", n);
}

void __0000000000101011_dis(uint16_t op)
{
    /* rte */
    fprintf(stdout, "rte\n");
}

void __0000000001011000_dis(uint16_t op)
{
    /* sets */
    fprintf(stdout, "sets\n");
}

void __0000000000011000_dis(uint16_t op)
{
    /* sett */
    fprintf(stdout, "sett\n");
}

void __0000000000011011_dis(uint16_t op)
{
    /* sleep */
    fprintf(stdout, "sleep\n");
}

void __0000nnnn00000010_dis(uint16_t op)
{
    /* stc     sr,rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "stc     sr,r%d\n", n);
}

void __0000nnnn00010010_dis(uint16_t op)
{
    /* stc     gbr,rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "stc     gbr,r%d\n", n);
}

void __0000nnnn00100010_dis(uint16_t op)
{
    /* stc     vbr,rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "stc     vbr,r%d\n", n);
}

void __0000nnnn00110010_dis(uint16_t op)
{
    /* stc     ssr,rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "stc     ssr,r%d\n", n);
}

void __0000nnnn01000010_dis(uint16_t op)
{
    /* stc     spc,rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "stc     spc,r%d\n", n);
}

void __0000nnnn00111010_dis(uint16_t op)
{
    /* stc     sgr,rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "stc     sgr,r%d\n", n);
}

void __0000nnnn11111010_dis(uint16_t op)
{
    /* stc     dbr,rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "stc     dbr,r%d\n", n);
}

void __0000nnnn1mmm0010_dis(uint16_t op)
{
    /* stc     rm_bank,rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0x7;
    fprintf(stdout, "stc     r%d_bank,r%d\n", m, n);
}

void __0100nnnn00000011_dis(uint16_t op)
{
    /* stc.l   sr,@-rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "stc.l   sr,@-r%d\n", n);
}

void __0100nnnn00010011_dis(uint16_t op)
{
    /* stc.l   gbr,@-rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "stc.l   gbr,@-r%d\n", n);
}

void __0100nnnn00100011_dis(uint16_t op)
{
    /* stc.l   vbr,@-rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "stc.l   vbr,@-r%d\n", n);
}

void __0100nnnn00110011_dis(uint16_t op)
{
    /* stc.l   ssr,@-rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "stc.l   ssr,@-r%d\n", n);
}

void __0100nnnn01000011_dis(uint16_t op)
{
    /* stc.l   spc,@-rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "stc.l   spc,@-r%d\n", n);
}

void __0100nnnn00110010_dis(uint16_t op)
{
    /* stc.l   sgr,@-rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "stc.l   sgr,@-r%d\n", n);
}

void __0100nnnn11110010_dis(uint16_t op)
{
    /* stc.l   dbr,@-rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "stc.l   dbr,@-r%d\n", n);
}

void __0100nnnn1mmm0011_dis(uint16_t op)
{
    /* stc.l   rm_bank,@-rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0x7;
    fprintf(stdout, "stc.l   r%d_bank,@-r%d\n", m, n);
}

void __0000nnnn00001010_dis(uint16_t op)
{
    /* sts     mach,rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "sts     mach,r%d\n", n);
}

void __0000nnnn00011010_dis(uint16_t op)
{
    /* sts     macl,rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "sts     macl,r%d\n", n);
}

void __0000nnnn00101010_dis(uint16_t op)
{
    /* sts   pr,rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "sts   pr,r%d\n", n);
}

void __0100nnnn00000010_dis(uint16_t op)
{
    /* sts.l   mach,@-rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "sts.l   mach,@-r%d\n", n);
}

void __0100nnnn00010010_dis(uint16_t op)
{
    /* sts.l   macl,@-rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "sts.l   macl,@-r%d\n", n);
}

void __0100nnnn00100010_dis(uint16_t op)
{
    /* sts.l   pr,@-rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "sts.l   pr,@-r%d\n", n);
}

void __11000011iiiiiiii_dis(uint16_t op)
{
    /* trapa   #i */
    int8_t i = op&0xff;
    fprintf(stdout, "trapa   #%d\n", i);
}

void __1111nnnn10001101_dis(uint16_t op)
{
    /* fldi0   frn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "fldi0   fr%d\n", n);
}

void __1111nnnn10011101_dis(uint16_t op)
{
    /* fldi1   frn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "fldi1   fr%d\n", n);
}

void __1111nnnnmmmm1100_dis(uint16_t op)
{
    /* fmov    frm,frn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fmov    fr%d,fr%d\n", m, n);
}

void __1111nnnnmmmm1000_dis(uint16_t op)
{
    /* fmov.s  @rm,frn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fmov.s  @r%d,fr%d\n", m, n);
}

void __1111nnnnmmmm0110_dis(uint16_t op)
{
    /* fmov.s  @(r0,rm),frn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fmov.s  @(r0,r%d),fr%d\n", m, n);
}

void __1111nnnnmmmm1001_dis(uint16_t op)
{
    /* fmov.s  @rm+,frn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fmov.s  @r%d+,fr%d\n", m, n);
}

void __1111nnnnmmmm1010_dis(uint16_t op)
{
    /* fmov.s  frm,@rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fmov.s  fr%d,@r%d\n", m, n);
}

void __1111nnnnmmmm1011_dis(uint16_t op)
{
    /* fmov.s  frm,@-rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fmov.s  fr%d,@-r%d\n", m, n);
}

void __1111nnnnmmmm0111_dis(uint16_t op)
{
    /* fmov.s  frm,@(r0,rn) */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fmov.s  fr%d,@(r0,r%d)\n", m, n);
}

void __1111nnn0mmm01100_dis(uint16_t op)
{
    /* fmov    drm,drn */
    int8_t n = (op>>9)&0x7;
    int8_t m = (op>>5)&0x7;
    fprintf(stdout, "fmov    dr%d,dr%d\n", m, n);
}

void __1111nnn0mmmm1000_dis(uint16_t op)
{
    /* fmov    @rm,drn */
    int8_t n = (op>>9)&0x7;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fmov    @r%d,dr%d\n", m, n);
}

void __1111nnn0mmmm0110_dis(uint16_t op)
{
    /* fmov    @(r0,rm),drn */
    int8_t n = (op>>9)&0x7;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fmov    @(r0,r%d),dr%d\n", m, n);
}

void __1111nnn0mmmm1001_dis(uint16_t op)
{
    /* fmov    @rm+,drn */
    int8_t n = (op>>9)&0x7;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fmov    @r%d+,dr%d\n", m, n);
}

void __1111nnnnmmm01010_dis(uint16_t op)
{
    /* fmov    drm,@rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>5)&0x7;
    fprintf(stdout, "fmov    dr%d,@r%d\n", m, n);
}

void __1111nnnnmmm01011_dis(uint16_t op)
{
    /* fmov    drm,@-rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>5)&0x7;
    fprintf(stdout, "fmov    dr%d,@-r%d\n", m, n);
}

void __1111nnnnmmm00111_dis(uint16_t op)
{
    /* fmov    drm,@(r0,rn) */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>5)&0x7;
    fprintf(stdout, "fmov    dr%d,@(r0,r%d)\n", m, n);
}

void __1111mmmm00011101_dis(uint16_t op)
{
    /* flds    frm,fpul */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "flds    fr%d,fpul\n", m);
}

void __1111nnnn00001101_dis(uint16_t op)
{
    /* fsts    fpul,frn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "fsts    fpul,fr%d\n", n);
}

void __1111nnnn01011101_dis(uint16_t op)
{
    /* fabs    frn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "fabs    fr%d\n", n);
}

void __1111nnnnmmmm0000_dis(uint16_t op)
{
    /* fadd    frm,frn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fadd    fr%d,fr%d\n", m, n);
}

void __1111nnnnmmmm0100_dis(uint16_t op)
{
    /* fcmp/eq frm,frn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fcmp/eq fr%d,fr%d\n", m, n);
}

void __1111nnnnmmmm0101_dis(uint16_t op)
{
    /* fcmp/gt frm,frn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fcmp/gt fr%d,fr%d\n", m, n);
}

void __1111nnnnmmmm0011_dis(uint16_t op)
{
    /* fdiv    frm,frn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fdiv    fr%d,fr%d\n", m, n);
}

void __1111nnnn00101101_dis(uint16_t op)
{
    /* float   fpul,frn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "float   fpul,fr%d\n", n);
}

void __1111nnnnmmmm1110_dis(uint16_t op)
{
    /* fmac    fr0,frm,frn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fmac    fr0,fr%d,fr%d\n", m, n);
}

void __1111nnnnmmmm0010_dis(uint16_t op)
{
    /* fmul    frm,frn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fmul    fr%d,fr%d\n", m, n);
}

void __1111nnnn01001101_dis(uint16_t op)
{
    /* fneg    frn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "fneg    fr%d\n", n);
}

void __1111nnnn01101101_dis(uint16_t op)
{
    /* fsqrt   frn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "fsqrt   fr%d\n", n);
}

void __1111nnnnmmmm0001_dis(uint16_t op)
{
    /* fsub    frm,frn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fsub    fr%d,fr%d\n", m, n);
}

void __1111mmmm00111101_dis(uint16_t op)
{
    /* ftrc    frm,fpul */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "ftrc    fr%d,fpul\n", m);
}

void __1111nnn001011101_dis(uint16_t op)
{
    /* fabs    drn */
    int8_t n = (op>>9)&0x7;
    fprintf(stdout, "fabs    dr%d\n", n);
}

void __1111nnn0mmm00000_dis(uint16_t op)
{
    /* fadd    drm,drn */
    int8_t n = (op>>9)&0x7;
    int8_t m = (op>>5)&0x7;
    fprintf(stdout, "fadd    dr%d,dr%d\n", m, n);
}

void __1111nnn0mmm00100_dis(uint16_t op)
{
    /* fcmp/eq drm,drn */
    int8_t n = (op>>9)&0x7;
    int8_t m = (op>>5)&0x7;
    fprintf(stdout, "fcmp/eq dr%d,dr%d\n", m, n);
}

void __1111nnn0mmm00101_dis(uint16_t op)
{
    /* fcmp/gt drm,drn */
    int8_t n = (op>>9)&0x7;
    int8_t m = (op>>5)&0x7;
    fprintf(stdout, "fcmp/gt dr%d,dr%d\n", m, n);
}

void __1111nnn0mmm00011_dis(uint16_t op)
{
    /* fdiv    drm,drn */
    int8_t n = (op>>9)&0x7;
    int8_t m = (op>>5)&0x7;
    fprintf(stdout, "fdiv    dr%d,dr%d\n", m, n);
}

void __1111mmm010111101_dis(uint16_t op)
{
    /* fcnvds  drm,fpul */
    int8_t m = (op>>9)&0x7;
    fprintf(stdout, "fcnvds  dr%d,fpul\n", m);
}

void __1111nnn010101101_dis(uint16_t op)
{
    /* fcnvsd  fpul,drn */
    int8_t n = (op>>9)&0x7;
    fprintf(stdout, "fcnvsd  fpul,dr%d\n", n);
}

void __1111nnn000101101_dis(uint16_t op)
{
    /* float   fpul,drn */
    int8_t n = (op>>9)&0x7;
    fprintf(stdout, "float   fpul,dr%d\n", n);
}

void __1111nnn0mmm00010_dis(uint16_t op)
{
    /* fmul    drm,drn */
    int8_t n = (op>>9)&0x7;
    int8_t m = (op>>5)&0x7;
    fprintf(stdout, "fmul    dr%d,dr%d\n", m, n);
}

void __1111nnn001001101_dis(uint16_t op)
{
    /* fneg    drn */
    int8_t n = (op>>9)&0x7;
    fprintf(stdout, "fneg    dr%d\n", n);
}

void __1111nnn001101101_dis(uint16_t op)
{
    /* fsqrt   drn */
    int8_t n = (op>>9)&0x7;
    fprintf(stdout, "fsqrt   dr%d\n", n);
}

void __1111nnn0mmm00001_dis(uint16_t op)
{
    /* fsub    drm,drn */
    int8_t n = (op>>9)&0x7;
    int8_t m = (op>>5)&0x7;
    fprintf(stdout, "fsub    dr%d,dr%d\n", m, n);
}

void __1111mmm000111101_dis(uint16_t op)
{
    /* ftrc    drm,fpul */
    int8_t m = (op>>9)&0x7;
    fprintf(stdout, "ftrc    dr%d,fpul\n", m);
}

void __0100mmmm01101010_dis(uint16_t op)
{
    /* lds     rm,fpscr */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "lds     r%d,fpscr\n", m);
}

void __0100mmmm01011010_dis(uint16_t op)
{
    /* lds     rm,fpul */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "lds     r%d,fpul\n", m);
}

void __0100mmmm01100110_dis(uint16_t op)
{
    /* lds.l   @rm+,fpscr */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "lds.l   @r%d+,fpscr\n", m);
}

void __0100mmmm01010110_dis(uint16_t op)
{
    /* lds.l   @rm+,fpul */
    int8_t m = (op>>8)&0xf;
    fprintf(stdout, "lds.l   @r%d+,fpul\n", m);
}

void __0000nnnn01101010_dis(uint16_t op)
{
    /* sts     fpscr,rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "sts     fpscr,r%d\n", n);
}

void __0000nnnn01011010_dis(uint16_t op)
{
    /* sts     fpul,rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "sts     fpul,r%d\n", n);
}

void __0100nnnn01100010_dis(uint16_t op)
{
    /* sts.l   fpscr,@-rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "sts.l   fpscr,@-r%d\n", n);
}

void __0100nnnn01010010_dis(uint16_t op)
{
    /* sts.l   fpul,@-rn */
    int8_t n = (op>>8)&0xf;
    fprintf(stdout, "sts.l   fpul,@-r%d\n", n);
}

void __1111nnn1mmm01100_dis(uint16_t op)
{
    /* fmov    drm,xdn */
    int8_t n = (op>>9)&0x7;
    int8_t m = (op>>5)&0x7;
    fprintf(stdout, "fmov    dr%d,xd%d\n", m, n);
}

void __1111nnn0mmm11100_dis(uint16_t op)
{
    /* fmov    xdm,drn */
    int8_t n = (op>>9)&0x7;
    int8_t m = (op>>5)&0x7;
    fprintf(stdout, "fmov    xd%d,dr%d\n", m, n);
}

void __1111nnn1mmm11100_dis(uint16_t op)
{
    /* fmov    xdm,xdn */
    int8_t n = (op>>9)&0x7;
    int8_t m = (op>>5)&0x7;
    fprintf(stdout, "fmov    xd%d,xd%d\n", m, n);
}

void __1111nnn1mmmm1000_dis(uint16_t op)
{
    /* fmov    @rm,xdn */
    int8_t n = (op>>9)&0x7;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fmov    @r%d,xd%d\n", m, n);
}

void __1111nnn1mmmm1001_dis(uint16_t op)
{
    /* fmov    @rm+,xdn */
    int8_t n = (op>>9)&0x7;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fmov    @r%d+,xd%d\n", m, n);
}

void __1111nnn1mmmm0110_dis(uint16_t op)
{
    /* fmov    @(r0,rm),drn */
    int8_t n = (op>>9)&0x7;
    int8_t m = (op>>4)&0xf;
    fprintf(stdout, "fmov    @(r0,r%d),dr%d\n", m, n);
}

void __1111nnnnmmm11010_dis(uint16_t op)
{
    /* fmov    xdm,@rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>5)&0x7;
    fprintf(stdout, "fmov    xd%d,@r%d\n", m, n);
}

void __1111nnnnmmm11011_dis(uint16_t op)
{
    /* fmov    xdm,@-rn */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>5)&0x7;
    fprintf(stdout, "fmov    xd%d,@-r%d\n", m, n);
}

void __1111nnnnmmm10111_dis(uint16_t op)
{
    /* fmov    xdm,@(r0,rn) */
    int8_t n = (op>>8)&0xf;
    int8_t m = (op>>5)&0x7;
    fprintf(stdout, "fmov    xd%d,@(r0,r%d)\n", m, n);
}

void __1111nnmm11101101_dis(uint16_t op)
{
    /* fipr    fvm,fvn */
    int8_t n = (op>>10)&0x3;
    int8_t m = (op>>8)&0x3;
    fprintf(stdout, "fipr    fv%d,fv%d\n", m, n);
}

void __1111nn0111111101_dis(uint16_t op)
{
    /* ftrv    xmtrx,fvn */
    int8_t n = (op>>10)&0x3;
    fprintf(stdout, "ftrv    xmtrx,fv%d\n", n);
}

void __1111101111111101_dis(uint16_t op)
{
    /* frchg */
    fprintf(stdout, "frchg\n");
}

void __1111001111111101_dis(uint16_t op)
{
    /* fschg */
    fprintf(stdout, "fschg\n");
}

#endif // SH7750_ENABLE_DISASSEMBLER
