/*********************************************
 * sh4opcode.h
 *
 * Header file with all the LUT definitions
 *
 * @author Roberto Cano <roberto dot cano at google mail>
 *
 * THIS FILE IS AUTOMATICALLY GENERATED.
 * DO NOT MODIFY!!!!
 *
 *********************************************/
#ifndef __SH4OPCODE_H__
#define __SH4OPCODE_H__

#include <stdint.h>

/* SH4 opcode processor type */
typedef void (*SH4OPProcesor_t)(uint16_t);

/* Forward declaration of all opcode interpreter processors */
void __0000000000000000(uint16_t op); /**< EXCEPTION */
void __1110nnnniiiiiiii(uint16_t op); /**< mov #i,Rn */
void __1001nnnndddddddd(uint16_t op); /**< mov.w @(d,PC),Rn */
void __1101nnnndddddddd(uint16_t op); /**< mov.l @(d,PC),Rn */
void __0110nnnnmmmm0011(uint16_t op); /**< mov Rm,Rn */
void __0010nnnnmmmm0000(uint16_t op); /**< mov.b Rm,@Rn */
void __0010nnnnmmmm0001(uint16_t op); /**< mov.w Rm,@Rn */
void __0010nnnnmmmm0010(uint16_t op); /**< mov.l Rm,@Rn */
void __0110nnnnmmmm0000(uint16_t op); /**< mov.b @Rm,Rn */
void __0110nnnnmmmm0001(uint16_t op); /**< mov.w @Rm,Rn */
void __0110nnnnmmmm0010(uint16_t op); /**< mov.l @Rm,Rn */
void __0010nnnnmmmm0100(uint16_t op); /**< mov.b Rm,@-Rn */
void __0010nnnnmmmm0101(uint16_t op); /**< mov.w Rm,@-Rn */
void __0010nnnnmmmm0110(uint16_t op); /**< mov.l Rm,@-Rn */
void __0110nnnnmmmm0100(uint16_t op); /**< mov.b @Rm+,Rn */
void __0110nnnnmmmm0101(uint16_t op); /**< mov.w @Rm+,Rn */
void __0110nnnnmmmm0110(uint16_t op); /**< mov.l @Rm+,Rn */
void __10000000nnnndddd(uint16_t op); /**< mov.b R0,@(d,Rn) */
void __10000001nnnndddd(uint16_t op); /**< mov.w R0,@(d,Rn) */
void __0001nnnnmmmmdddd(uint16_t op); /**< mov.l Rm,@(d,Rn) */
void __10000100mmmmdddd(uint16_t op); /**< mov.b @(d,Rm),R0 */
void __10000101mmmmdddd(uint16_t op); /**< mov.w @(d,Rm),R0 */
void __0101nnnnmmmmdddd(uint16_t op); /**< mov.l @(d,Rm),Rn */
void __0000nnnnmmmm0100(uint16_t op); /**< mov.b Rm,@(R0,Rn) */
void __0000nnnnmmmm0101(uint16_t op); /**< mov.w Rm,@(R0,Rn) */
void __0000nnnnmmmm0110(uint16_t op); /**< mov.l Rm,@(R0,Rn) */
void __0000nnnnmmmm1100(uint16_t op); /**< mov.b @(R0,Rm),Rn */
void __0000nnnnmmmm1101(uint16_t op); /**< mov.w @(R0,Rm),Rn */
void __0000nnnnmmmm1110(uint16_t op); /**< mov.l @(R0,Rm),Rn */
void __11000000dddddddd(uint16_t op); /**< mov.b R0,@(d,GBR) */
void __11000001dddddddd(uint16_t op); /**< mov.w R0,@(d,GBR) */
void __11000010dddddddd(uint16_t op); /**< mov.l R0,@(d,GBR) */
void __11000100dddddddd(uint16_t op); /**< mov.b @(d,GBR),R0 */
void __11000101dddddddd(uint16_t op); /**< mov.w @(d,GBR),R0 */
void __11000110dddddddd(uint16_t op); /**< mov.l @(d,GBR),R0 */
void __11000111dddddddd(uint16_t op); /**< mova @(d,PC),R0 */
void __0000nnnn00101001(uint16_t op); /**< movt Rn */
void __0110nnnnmmmm1000(uint16_t op); /**< swap.b Rm,Rn */
void __0110nnnnmmmm1001(uint16_t op); /**< swap.w Rm,Rn */
void __0010nnnnmmmm1101(uint16_t op); /**< xtrct Rm,Rn */
void __0011nnnnmmmm1100(uint16_t op); /**< add Rm,Rn */
void __0111nnnniiiiiiii(uint16_t op); /**< add #i,Rn */
void __0011nnnnmmmm1110(uint16_t op); /**< addc Rm,Rn */
void __0011nnnnmmmm1111(uint16_t op); /**< addv Rm,Rn */
void __10001000iiiiiiii(uint16_t op); /**< cmp/eq #i,R0 */
void __0011nnnnmmmm0000(uint16_t op); /**< cmp/eq Rm,Rn */
void __0011nnnnmmmm0010(uint16_t op); /**< cmp/hs Rm,Rn */
void __0011nnnnmmmm0011(uint16_t op); /**< cmp/ge Rm,Rn */
void __0011nnnnmmmm0110(uint16_t op); /**< cmp/hi Rm,Rn */
void __0011nnnnmmmm0111(uint16_t op); /**< cmp/gt Rm,Rn */
void __0100nnnn00010001(uint16_t op); /**< cmp/pz Rn */
void __0100nnnn00010101(uint16_t op); /**< cmp/pl Rn */
void __0010nnnnmmmm1100(uint16_t op); /**< cmp/str Rm,Rn */
void __0011nnnnmmmm0100(uint16_t op); /**< div1 Rm,Rn */
void __0010nnnnmmmm0111(uint16_t op); /**< div0s Rm,Rn */
void __0000000000011001(uint16_t op); /**< div0u */
void __0011nnnnmmmm1101(uint16_t op); /**< dmuls.l Rm,Rn */
void __0011nnnnmmmm0101(uint16_t op); /**< dmulu.l Rm,Rn */
void __0100nnnn00010000(uint16_t op); /**< dt Rn */
void __0110nnnnmmmm1110(uint16_t op); /**< exts.b Rm,Rn */
void __0110nnnnmmmm1111(uint16_t op); /**< exts.w Rm,Rn */
void __0110nnnnmmmm1100(uint16_t op); /**< extu.b Rm,Rn */
void __0110nnnnmmmm1101(uint16_t op); /**< extu.w Rm,Rn */
void __0000nnnnmmmm1111(uint16_t op); /**< mac.l @Rm+,@Rn+ */
void __0100nnnnmmmm1111(uint16_t op); /**< mac.w @Rm+,@Rn+ */
void __0000nnnnmmmm0111(uint16_t op); /**< mul.l Rm,Rn */
void __0010nnnnmmmm1111(uint16_t op); /**< muls.w Rm,Rn */
void __0010nnnnmmmm1110(uint16_t op); /**< mulu.w Rm,Rn */
void __0110nnnnmmmm1011(uint16_t op); /**< neg Rm,Rn */
void __0110nnnnmmmm1010(uint16_t op); /**< negc Rm,Rn */
void __0011nnnnmmmm1000(uint16_t op); /**< sub Rm,Rn */
void __0011nnnnmmmm1010(uint16_t op); /**< subc Rm,Rn */
void __0011nnnnmmmm1011(uint16_t op); /**< subv Rm,Rn */
void __0010nnnnmmmm1001(uint16_t op); /**< and Rm,Rn */
void __11001001iiiiiiii(uint16_t op); /**< and #i,R0 */
void __11001101iiiiiiii(uint16_t op); /**< and.b #i,@(R0,GBR) */
void __0110nnnnmmmm0111(uint16_t op); /**< not Rm,Rn */
void __0010nnnnmmmm1011(uint16_t op); /**< or Rm,Rn */
void __11001011iiiiiiii(uint16_t op); /**< or #i,R0 */
void __11001111iiiiiiii(uint16_t op); /**< or.b #i,@(R0,GBR) */
void __0100nnnn00011011(uint16_t op); /**< tas.b @Rn */
void __0010nnnnmmmm1000(uint16_t op); /**< tst Rm,Rn */
void __11001000iiiiiiii(uint16_t op); /**< tst #i,R0 */
void __11001100iiiiiiii(uint16_t op); /**< tst.b #i,@(R0,GBR) */
void __0010nnnnmmmm1010(uint16_t op); /**< xor Rm,Rn */
void __11001010iiiiiiii(uint16_t op); /**< xor #i,R0 */
void __11001110iiiiiiii(uint16_t op); /**< xor.b #i,@(R0,GBR) */
void __0100nnnn00000100(uint16_t op); /**< rotl Rn */
void __0100nnnn00000101(uint16_t op); /**< rotr Rn */
void __0100nnnn00100100(uint16_t op); /**< rotcl Rn */
void __0100nnnn00100101(uint16_t op); /**< rotcr Rn */
void __0100nnnnmmmm1100(uint16_t op); /**< shad Rm,Rn */
void __0100nnnn00100000(uint16_t op); /**< shal Rn */
void __0100nnnn00100001(uint16_t op); /**< shar Rn */
void __0100nnnnmmmm1101(uint16_t op); /**< shld Rm,Rn */
void __0100nnnn00000000(uint16_t op); /**< shll Rn */
void __0100nnnn00000001(uint16_t op); /**< shlr Rn */
void __0100nnnn00001000(uint16_t op); /**< shll2 Rn */
void __0100nnnn00001001(uint16_t op); /**< shlr2 Rn */
void __0100nnnn00011000(uint16_t op); /**< shll8 Rn */
void __0100nnnn00011001(uint16_t op); /**< shlr8 Rn */
void __0100nnnn00101000(uint16_t op); /**< shll16 Rn */
void __0100nnnn00101001(uint16_t op); /**< shlr16 Rn */
void __10001011dddddddd(uint16_t op); /**< bf d */
void __10001111dddddddd(uint16_t op); /**< bf/s d */
void __10001001dddddddd(uint16_t op); /**< bt d */
void __10001101dddddddd(uint16_t op); /**< bt/s d */
void __1010dddddddddddd(uint16_t op); /**< bra d */
void __0000nnnn00100011(uint16_t op); /**< braf Rn */
void __1011dddddddddddd(uint16_t op); /**< bsr d */
void __0000nnnn00000011(uint16_t op); /**< bsrf Rn */
void __0100nnnn00101011(uint16_t op); /**< jmp @Rn */
void __0100nnnn00001011(uint16_t op); /**< jsr @Rn */
void __0000000000001011(uint16_t op); /**< rts */
void __0000000000101000(uint16_t op); /**< clrmac */
void __0000000001001000(uint16_t op); /**< clrs */
void __0000000000001000(uint16_t op); /**< clrt */
void __0100mmmm00001110(uint16_t op); /**< ldc Rm,SR */
void __0100mmmm00011110(uint16_t op); /**< ldc Rm,GBR */
void __0100mmmm00101110(uint16_t op); /**< ldc Rm,VBR */
void __0100mmmm00111110(uint16_t op); /**< ldc Rm,SSR */
void __0100mmmm01001110(uint16_t op); /**< ldc Rm,SPC */
void __0100mmmm11111010(uint16_t op); /**< ldc Rm,DBR */
void __0100mmmm1nnn1110(uint16_t op); /**< ldc Rm,Rn_BANK */
void __0100mmmm00000111(uint16_t op); /**< ldc.l @Rm+,SR */
void __0100mmmm00010111(uint16_t op); /**< ldc.l @Rm+,GBR */
void __0100mmmm00100111(uint16_t op); /**< ldc.l @Rm+,VBR */
void __0100mmmm00110111(uint16_t op); /**< ldc.l @Rm+,SSR */
void __0100mmmm01000111(uint16_t op); /**< ldc.l @Rm+,SPC */
void __0100mmmm11110110(uint16_t op); /**< ldc.l @Rm+,DBR */
void __0100mmmm1nnn0111(uint16_t op); /**< ldc.l @Rm+,Rn_BANK */
void __0100mmmm00001010(uint16_t op); /**< lds Rm,MACH */
void __0100mmmm00011010(uint16_t op); /**< lds Rm,MACL */
void __0100mmmm00101010(uint16_t op); /**< lds Rm,PR */
void __0100mmmm00000110(uint16_t op); /**< lds.l @Rm+,MACH */
void __0100mmmm00010110(uint16_t op); /**< lds.l @Rm+,MACL */
void __0100mmmm00100110(uint16_t op); /**< lds.l @Rm+,PR */
void __0000000000111000(uint16_t op); /**< ldtlb */
void __0000nnnn11000011(uint16_t op); /**< movca.l R0,@Rn */
void __0000000000001001(uint16_t op); /**< nop */
void __0000nnnn10010011(uint16_t op); /**< ocbi @Rn */
void __0000nnnn10100011(uint16_t op); /**< ocbp @Rn */
void __0000nnnn10110011(uint16_t op); /**< ocbwb @Rn */
void __0000nnnn10000011(uint16_t op); /**< pref @Rn */
void __0000000000101011(uint16_t op); /**< rte */
void __0000000001011000(uint16_t op); /**< sets */
void __0000000000011000(uint16_t op); /**< sett */
void __0000000000011011(uint16_t op); /**< sleep */
void __0000nnnn00000010(uint16_t op); /**< stc SR,Rn */
void __0000nnnn00010010(uint16_t op); /**< stc GBR,Rn */
void __0000nnnn00100010(uint16_t op); /**< stc VBR,Rn */
void __0000nnnn00110010(uint16_t op); /**< stc SSR,Rn */
void __0000nnnn01000010(uint16_t op); /**< stc SPC,Rn */
void __0000nnnn00111010(uint16_t op); /**< stc SGR,Rn */
void __0000nnnn11111010(uint16_t op); /**< stc DBR,Rn */
void __0000nnnn1mmm0010(uint16_t op); /**< stc Rm_BANK,Rn */
void __0100nnnn00000011(uint16_t op); /**< stc.l SR,@-Rn */
void __0100nnnn00010011(uint16_t op); /**< stc.l GBR,@-Rn */
void __0100nnnn00100011(uint16_t op); /**< stc.l VBR,@-Rn */
void __0100nnnn00110011(uint16_t op); /**< stc.l SSR,@-Rn */
void __0100nnnn01000011(uint16_t op); /**< stc.l SPC,@-Rn */
void __0100nnnn00110010(uint16_t op); /**< stc.l SGR,@-Rn */
void __0100nnnn11110010(uint16_t op); /**< stc.l DBR,@-Rn */
void __0100nnnn1mmm0011(uint16_t op); /**< stc.l Rm_BANK,@-Rn */
void __0000nnnn00001010(uint16_t op); /**< sts MACH,Rn */
void __0000nnnn00011010(uint16_t op); /**< sts MACL,Rn */
void __0000nnnn00101010(uint16_t op); /**< sts PR,Rn */
void __0100nnnn00000010(uint16_t op); /**< sts.l MACH,@-Rn */
void __0100nnnn00010010(uint16_t op); /**< sts.l MACL,@-Rn */
void __0100nnnn00100010(uint16_t op); /**< sts.l PR,@-Rn */
void __11000011iiiiiiii(uint16_t op); /**< trapa #i */
void __1111nnnn10001101(uint16_t op); /**< fldi0 FRn */
void __1111nnnn10011101(uint16_t op); /**< fldi1 FRn */
void __1111nnnnmmmm1100(uint16_t op); /**< fmov FRm,FRn */
void __1111nnnnmmmm1000(uint16_t op); /**< fmov.s @Rm,FRn */
void __1111nnnnmmmm0110(uint16_t op); /**< fmov.s @(R0,Rm),FRn */
void __1111nnnnmmmm1001(uint16_t op); /**< fmov.s @Rm+,FRn */
void __1111nnnnmmmm1010(uint16_t op); /**< fmov.s FRm,@Rn */
void __1111nnnnmmmm1011(uint16_t op); /**< fmov.s FRm,@-Rn */
void __1111nnnnmmmm0111(uint16_t op); /**< fmov.s FRm,@(R0,Rn) */
void __1111nnn0mmm01100(uint16_t op); /**< fmov DRm,DRn */
void __1111nnn0mmmm1000(uint16_t op); /**< fmov @Rm,DRn */
void __1111nnn0mmmm0110(uint16_t op); /**< fmov @(R0,Rm),DRn */
void __1111nnn0mmmm1001(uint16_t op); /**< fmov @Rm+,DRn */
void __1111nnnnmmm01010(uint16_t op); /**< fmov DRm,@Rn */
void __1111nnnnmmm01011(uint16_t op); /**< fmov DRm,@-Rn */
void __1111nnnnmmm00111(uint16_t op); /**< fmov DRm,@(R0,Rn) */
void __1111mmmm00011101(uint16_t op); /**< flds FRm,FPUL */
void __1111nnnn00001101(uint16_t op); /**< fsts FPUL,FRn */
void __1111nnnn01011101(uint16_t op); /**< fabs FRn */
void __1111nnnnmmmm0000(uint16_t op); /**< fadd FRm,FRn */
void __1111nnnnmmmm0100(uint16_t op); /**< fcmp/eq FRm,FRn */
void __1111nnnnmmmm0101(uint16_t op); /**< fcmp/gt FRm,FRn */
void __1111nnnnmmmm0011(uint16_t op); /**< fdiv FRm,FRn */
void __1111nnnn00101101(uint16_t op); /**< float FPUL,FRn */
void __1111nnnnmmmm1110(uint16_t op); /**< fmac FR0,FRm,FRn */
void __1111nnnnmmmm0010(uint16_t op); /**< fmul FRm,FRn */
void __1111nnnn01001101(uint16_t op); /**< fneg FRn */
void __1111nnnn01101101(uint16_t op); /**< fsqrt FRn */
void __1111nnnnmmmm0001(uint16_t op); /**< fsub FRm,FRn */
void __1111mmmm00111101(uint16_t op); /**< ftrc FRm,FPUL */
void __1111nnn001011101(uint16_t op); /**< fabs DRn */
void __1111nnn0mmm00000(uint16_t op); /**< fadd DRm,DRn */
void __1111nnn0mmm00100(uint16_t op); /**< fcmp/eq DRm,DRn */
void __1111nnn0mmm00101(uint16_t op); /**< fcmp/gt DRm,DRn */
void __1111nnn0mmm00011(uint16_t op); /**< fdiv DRm,DRn */
void __1111mmm010111101(uint16_t op); /**< fcnvds DRm,FPUL */
void __1111nnn010101101(uint16_t op); /**< fcnvsd FPUL,DRn */
void __1111nnn000101101(uint16_t op); /**< float FPUL,DRn */
void __1111nnn0mmm00010(uint16_t op); /**< fmul DRm,DRn */
void __1111nnn001001101(uint16_t op); /**< fneg DRn */
void __1111nnn001101101(uint16_t op); /**< fsqrt DRn */
void __1111nnn0mmm00001(uint16_t op); /**< fsub DRm,DRn */
void __1111mmm000111101(uint16_t op); /**< ftrc DRm,FPUL */
void __0100mmmm01101010(uint16_t op); /**< lds Rm,FPSCR */
void __0100mmmm01011010(uint16_t op); /**< lds Rm,FPUL */
void __0100mmmm01100110(uint16_t op); /**< lds.l @Rm+,FPSCR */
void __0100mmmm01010110(uint16_t op); /**< lds.l @Rm+,FPUL */
void __0000nnnn01101010(uint16_t op); /**< sts FPSCR,Rn */
void __0000nnnn01011010(uint16_t op); /**< sts FPUL,Rn */
void __0100nnnn01100010(uint16_t op); /**< sts.l FPSCR,@-Rn */
void __0100nnnn01010010(uint16_t op); /**< sts.l FPUL,@-Rn */
void __1111nnn1mmm01100(uint16_t op); /**< fmov DRm,XDn */
void __1111nnn0mmm11100(uint16_t op); /**< fmov XDm,DRn */
void __1111nnn1mmm11100(uint16_t op); /**< fmov XDm,XDn */
void __1111nnn1mmmm1000(uint16_t op); /**< fmov @Rm,XDn */
void __1111nnn1mmmm1001(uint16_t op); /**< fmov @Rm+,XDn */
void __1111nnn1mmmm0110(uint16_t op); /**< fmov @(R0,Rm),DRn */
void __1111nnnnmmm11010(uint16_t op); /**< fmov XDm,@Rn */
void __1111nnnnmmm11011(uint16_t op); /**< fmov XDm,@-Rn */
void __1111nnnnmmm10111(uint16_t op); /**< fmov XDm,@(R0,Rn) */
void __1111nnmm11101101(uint16_t op); /**< fipr FVm,FVn */
void __1111nn0111111101(uint16_t op); /**< ftrv XMTRX,FVn */
void __1111101111111101(uint16_t op); /**< frchg */
void __1111001111111101(uint16_t op); /**< fschg */

/* Opcodes interpreter lookup table declaration */
extern SH4OPProcesor_t SH7750InterpLUT[];

/* Forward declaration of all opcode disasembler processors */
#ifdef SH7750_ENABLE_DISASSEMBLER
void __0000000000000000_dis(uint16_t op); /**< EXCEPTION */
void __1110nnnniiiiiiii_dis(uint16_t op); /**< mov #i,Rn */
void __1001nnnndddddddd_dis(uint16_t op); /**< mov.w @(d,PC),Rn */
void __1101nnnndddddddd_dis(uint16_t op); /**< mov.l @(d,PC),Rn */
void __0110nnnnmmmm0011_dis(uint16_t op); /**< mov Rm,Rn */
void __0010nnnnmmmm0000_dis(uint16_t op); /**< mov.b Rm,@Rn */
void __0010nnnnmmmm0001_dis(uint16_t op); /**< mov.w Rm,@Rn */
void __0010nnnnmmmm0010_dis(uint16_t op); /**< mov.l Rm,@Rn */
void __0110nnnnmmmm0000_dis(uint16_t op); /**< mov.b @Rm,Rn */
void __0110nnnnmmmm0001_dis(uint16_t op); /**< mov.w @Rm,Rn */
void __0110nnnnmmmm0010_dis(uint16_t op); /**< mov.l @Rm,Rn */
void __0010nnnnmmmm0100_dis(uint16_t op); /**< mov.b Rm,@-Rn */
void __0010nnnnmmmm0101_dis(uint16_t op); /**< mov.w Rm,@-Rn */
void __0010nnnnmmmm0110_dis(uint16_t op); /**< mov.l Rm,@-Rn */
void __0110nnnnmmmm0100_dis(uint16_t op); /**< mov.b @Rm+,Rn */
void __0110nnnnmmmm0101_dis(uint16_t op); /**< mov.w @Rm+,Rn */
void __0110nnnnmmmm0110_dis(uint16_t op); /**< mov.l @Rm+,Rn */
void __10000000nnnndddd_dis(uint16_t op); /**< mov.b R0,@(d,Rn) */
void __10000001nnnndddd_dis(uint16_t op); /**< mov.w R0,@(d,Rn) */
void __0001nnnnmmmmdddd_dis(uint16_t op); /**< mov.l Rm,@(d,Rn) */
void __10000100mmmmdddd_dis(uint16_t op); /**< mov.b @(d,Rm),R0 */
void __10000101mmmmdddd_dis(uint16_t op); /**< mov.w @(d,Rm),R0 */
void __0101nnnnmmmmdddd_dis(uint16_t op); /**< mov.l @(d,Rm),Rn */
void __0000nnnnmmmm0100_dis(uint16_t op); /**< mov.b Rm,@(R0,Rn) */
void __0000nnnnmmmm0101_dis(uint16_t op); /**< mov.w Rm,@(R0,Rn) */
void __0000nnnnmmmm0110_dis(uint16_t op); /**< mov.l Rm,@(R0,Rn) */
void __0000nnnnmmmm1100_dis(uint16_t op); /**< mov.b @(R0,Rm),Rn */
void __0000nnnnmmmm1101_dis(uint16_t op); /**< mov.w @(R0,Rm),Rn */
void __0000nnnnmmmm1110_dis(uint16_t op); /**< mov.l @(R0,Rm),Rn */
void __11000000dddddddd_dis(uint16_t op); /**< mov.b R0,@(d,GBR) */
void __11000001dddddddd_dis(uint16_t op); /**< mov.w R0,@(d,GBR) */
void __11000010dddddddd_dis(uint16_t op); /**< mov.l R0,@(d,GBR) */
void __11000100dddddddd_dis(uint16_t op); /**< mov.b @(d,GBR),R0 */
void __11000101dddddddd_dis(uint16_t op); /**< mov.w @(d,GBR),R0 */
void __11000110dddddddd_dis(uint16_t op); /**< mov.l @(d,GBR),R0 */
void __11000111dddddddd_dis(uint16_t op); /**< mova @(d,PC),R0 */
void __0000nnnn00101001_dis(uint16_t op); /**< movt Rn */
void __0110nnnnmmmm1000_dis(uint16_t op); /**< swap.b Rm,Rn */
void __0110nnnnmmmm1001_dis(uint16_t op); /**< swap.w Rm,Rn */
void __0010nnnnmmmm1101_dis(uint16_t op); /**< xtrct Rm,Rn */
void __0011nnnnmmmm1100_dis(uint16_t op); /**< add Rm,Rn */
void __0111nnnniiiiiiii_dis(uint16_t op); /**< add #i,Rn */
void __0011nnnnmmmm1110_dis(uint16_t op); /**< addc Rm,Rn */
void __0011nnnnmmmm1111_dis(uint16_t op); /**< addv Rm,Rn */
void __10001000iiiiiiii_dis(uint16_t op); /**< cmp/eq #i,R0 */
void __0011nnnnmmmm0000_dis(uint16_t op); /**< cmp/eq Rm,Rn */
void __0011nnnnmmmm0010_dis(uint16_t op); /**< cmp/hs Rm,Rn */
void __0011nnnnmmmm0011_dis(uint16_t op); /**< cmp/ge Rm,Rn */
void __0011nnnnmmmm0110_dis(uint16_t op); /**< cmp/hi Rm,Rn */
void __0011nnnnmmmm0111_dis(uint16_t op); /**< cmp/gt Rm,Rn */
void __0100nnnn00010001_dis(uint16_t op); /**< cmp/pz Rn */
void __0100nnnn00010101_dis(uint16_t op); /**< cmp/pl Rn */
void __0010nnnnmmmm1100_dis(uint16_t op); /**< cmp/str Rm,Rn */
void __0011nnnnmmmm0100_dis(uint16_t op); /**< div1 Rm,Rn */
void __0010nnnnmmmm0111_dis(uint16_t op); /**< div0s Rm,Rn */
void __0000000000011001_dis(uint16_t op); /**< div0u */
void __0011nnnnmmmm1101_dis(uint16_t op); /**< dmuls.l Rm,Rn */
void __0011nnnnmmmm0101_dis(uint16_t op); /**< dmulu.l Rm,Rn */
void __0100nnnn00010000_dis(uint16_t op); /**< dt Rn */
void __0110nnnnmmmm1110_dis(uint16_t op); /**< exts.b Rm,Rn */
void __0110nnnnmmmm1111_dis(uint16_t op); /**< exts.w Rm,Rn */
void __0110nnnnmmmm1100_dis(uint16_t op); /**< extu.b Rm,Rn */
void __0110nnnnmmmm1101_dis(uint16_t op); /**< extu.w Rm,Rn */
void __0000nnnnmmmm1111_dis(uint16_t op); /**< mac.l @Rm+,@Rn+ */
void __0100nnnnmmmm1111_dis(uint16_t op); /**< mac.w @Rm+,@Rn+ */
void __0000nnnnmmmm0111_dis(uint16_t op); /**< mul.l Rm,Rn */
void __0010nnnnmmmm1111_dis(uint16_t op); /**< muls.w Rm,Rn */
void __0010nnnnmmmm1110_dis(uint16_t op); /**< mulu.w Rm,Rn */
void __0110nnnnmmmm1011_dis(uint16_t op); /**< neg Rm,Rn */
void __0110nnnnmmmm1010_dis(uint16_t op); /**< negc Rm,Rn */
void __0011nnnnmmmm1000_dis(uint16_t op); /**< sub Rm,Rn */
void __0011nnnnmmmm1010_dis(uint16_t op); /**< subc Rm,Rn */
void __0011nnnnmmmm1011_dis(uint16_t op); /**< subv Rm,Rn */
void __0010nnnnmmmm1001_dis(uint16_t op); /**< and Rm,Rn */
void __11001001iiiiiiii_dis(uint16_t op); /**< and #i,R0 */
void __11001101iiiiiiii_dis(uint16_t op); /**< and.b #i,@(R0,GBR) */
void __0110nnnnmmmm0111_dis(uint16_t op); /**< not Rm,Rn */
void __0010nnnnmmmm1011_dis(uint16_t op); /**< or Rm,Rn */
void __11001011iiiiiiii_dis(uint16_t op); /**< or #i,R0 */
void __11001111iiiiiiii_dis(uint16_t op); /**< or.b #i,@(R0,GBR) */
void __0100nnnn00011011_dis(uint16_t op); /**< tas.b @Rn */
void __0010nnnnmmmm1000_dis(uint16_t op); /**< tst Rm,Rn */
void __11001000iiiiiiii_dis(uint16_t op); /**< tst #i,R0 */
void __11001100iiiiiiii_dis(uint16_t op); /**< tst.b #i,@(R0,GBR) */
void __0010nnnnmmmm1010_dis(uint16_t op); /**< xor Rm,Rn */
void __11001010iiiiiiii_dis(uint16_t op); /**< xor #i,R0 */
void __11001110iiiiiiii_dis(uint16_t op); /**< xor.b #i,@(R0,GBR) */
void __0100nnnn00000100_dis(uint16_t op); /**< rotl Rn */
void __0100nnnn00000101_dis(uint16_t op); /**< rotr Rn */
void __0100nnnn00100100_dis(uint16_t op); /**< rotcl Rn */
void __0100nnnn00100101_dis(uint16_t op); /**< rotcr Rn */
void __0100nnnnmmmm1100_dis(uint16_t op); /**< shad Rm,Rn */
void __0100nnnn00100000_dis(uint16_t op); /**< shal Rn */
void __0100nnnn00100001_dis(uint16_t op); /**< shar Rn */
void __0100nnnnmmmm1101_dis(uint16_t op); /**< shld Rm,Rn */
void __0100nnnn00000000_dis(uint16_t op); /**< shll Rn */
void __0100nnnn00000001_dis(uint16_t op); /**< shlr Rn */
void __0100nnnn00001000_dis(uint16_t op); /**< shll2 Rn */
void __0100nnnn00001001_dis(uint16_t op); /**< shlr2 Rn */
void __0100nnnn00011000_dis(uint16_t op); /**< shll8 Rn */
void __0100nnnn00011001_dis(uint16_t op); /**< shlr8 Rn */
void __0100nnnn00101000_dis(uint16_t op); /**< shll16 Rn */
void __0100nnnn00101001_dis(uint16_t op); /**< shlr16 Rn */
void __10001011dddddddd_dis(uint16_t op); /**< bf d */
void __10001111dddddddd_dis(uint16_t op); /**< bf/s d */
void __10001001dddddddd_dis(uint16_t op); /**< bt d */
void __10001101dddddddd_dis(uint16_t op); /**< bt/s d */
void __1010dddddddddddd_dis(uint16_t op); /**< bra d */
void __0000nnnn00100011_dis(uint16_t op); /**< braf Rn */
void __1011dddddddddddd_dis(uint16_t op); /**< bsr d */
void __0000nnnn00000011_dis(uint16_t op); /**< bsrf Rn */
void __0100nnnn00101011_dis(uint16_t op); /**< jmp @Rn */
void __0100nnnn00001011_dis(uint16_t op); /**< jsr @Rn */
void __0000000000001011_dis(uint16_t op); /**< rts */
void __0000000000101000_dis(uint16_t op); /**< clrmac */
void __0000000001001000_dis(uint16_t op); /**< clrs */
void __0000000000001000_dis(uint16_t op); /**< clrt */
void __0100mmmm00001110_dis(uint16_t op); /**< ldc Rm,SR */
void __0100mmmm00011110_dis(uint16_t op); /**< ldc Rm,GBR */
void __0100mmmm00101110_dis(uint16_t op); /**< ldc Rm,VBR */
void __0100mmmm00111110_dis(uint16_t op); /**< ldc Rm,SSR */
void __0100mmmm01001110_dis(uint16_t op); /**< ldc Rm,SPC */
void __0100mmmm11111010_dis(uint16_t op); /**< ldc Rm,DBR */
void __0100mmmm1nnn1110_dis(uint16_t op); /**< ldc Rm,Rn_BANK */
void __0100mmmm00000111_dis(uint16_t op); /**< ldc.l @Rm+,SR */
void __0100mmmm00010111_dis(uint16_t op); /**< ldc.l @Rm+,GBR */
void __0100mmmm00100111_dis(uint16_t op); /**< ldc.l @Rm+,VBR */
void __0100mmmm00110111_dis(uint16_t op); /**< ldc.l @Rm+,SSR */
void __0100mmmm01000111_dis(uint16_t op); /**< ldc.l @Rm+,SPC */
void __0100mmmm11110110_dis(uint16_t op); /**< ldc.l @Rm+,DBR */
void __0100mmmm1nnn0111_dis(uint16_t op); /**< ldc.l @Rm+,Rn_BANK */
void __0100mmmm00001010_dis(uint16_t op); /**< lds Rm,MACH */
void __0100mmmm00011010_dis(uint16_t op); /**< lds Rm,MACL */
void __0100mmmm00101010_dis(uint16_t op); /**< lds Rm,PR */
void __0100mmmm00000110_dis(uint16_t op); /**< lds.l @Rm+,MACH */
void __0100mmmm00010110_dis(uint16_t op); /**< lds.l @Rm+,MACL */
void __0100mmmm00100110_dis(uint16_t op); /**< lds.l @Rm+,PR */
void __0000000000111000_dis(uint16_t op); /**< ldtlb */
void __0000nnnn11000011_dis(uint16_t op); /**< movca.l R0,@Rn */
void __0000000000001001_dis(uint16_t op); /**< nop */
void __0000nnnn10010011_dis(uint16_t op); /**< ocbi @Rn */
void __0000nnnn10100011_dis(uint16_t op); /**< ocbp @Rn */
void __0000nnnn10110011_dis(uint16_t op); /**< ocbwb @Rn */
void __0000nnnn10000011_dis(uint16_t op); /**< pref @Rn */
void __0000000000101011_dis(uint16_t op); /**< rte */
void __0000000001011000_dis(uint16_t op); /**< sets */
void __0000000000011000_dis(uint16_t op); /**< sett */
void __0000000000011011_dis(uint16_t op); /**< sleep */
void __0000nnnn00000010_dis(uint16_t op); /**< stc SR,Rn */
void __0000nnnn00010010_dis(uint16_t op); /**< stc GBR,Rn */
void __0000nnnn00100010_dis(uint16_t op); /**< stc VBR,Rn */
void __0000nnnn00110010_dis(uint16_t op); /**< stc SSR,Rn */
void __0000nnnn01000010_dis(uint16_t op); /**< stc SPC,Rn */
void __0000nnnn00111010_dis(uint16_t op); /**< stc SGR,Rn */
void __0000nnnn11111010_dis(uint16_t op); /**< stc DBR,Rn */
void __0000nnnn1mmm0010_dis(uint16_t op); /**< stc Rm_BANK,Rn */
void __0100nnnn00000011_dis(uint16_t op); /**< stc.l SR,@-Rn */
void __0100nnnn00010011_dis(uint16_t op); /**< stc.l GBR,@-Rn */
void __0100nnnn00100011_dis(uint16_t op); /**< stc.l VBR,@-Rn */
void __0100nnnn00110011_dis(uint16_t op); /**< stc.l SSR,@-Rn */
void __0100nnnn01000011_dis(uint16_t op); /**< stc.l SPC,@-Rn */
void __0100nnnn00110010_dis(uint16_t op); /**< stc.l SGR,@-Rn */
void __0100nnnn11110010_dis(uint16_t op); /**< stc.l DBR,@-Rn */
void __0100nnnn1mmm0011_dis(uint16_t op); /**< stc.l Rm_BANK,@-Rn */
void __0000nnnn00001010_dis(uint16_t op); /**< sts MACH,Rn */
void __0000nnnn00011010_dis(uint16_t op); /**< sts MACL,Rn */
void __0000nnnn00101010_dis(uint16_t op); /**< sts PR,Rn */
void __0100nnnn00000010_dis(uint16_t op); /**< sts.l MACH,@-Rn */
void __0100nnnn00010010_dis(uint16_t op); /**< sts.l MACL,@-Rn */
void __0100nnnn00100010_dis(uint16_t op); /**< sts.l PR,@-Rn */
void __11000011iiiiiiii_dis(uint16_t op); /**< trapa #i */
void __1111nnnn10001101_dis(uint16_t op); /**< fldi0 FRn */
void __1111nnnn10011101_dis(uint16_t op); /**< fldi1 FRn */
void __1111nnnnmmmm1100_dis(uint16_t op); /**< fmov FRm,FRn */
void __1111nnnnmmmm1000_dis(uint16_t op); /**< fmov.s @Rm,FRn */
void __1111nnnnmmmm0110_dis(uint16_t op); /**< fmov.s @(R0,Rm),FRn */
void __1111nnnnmmmm1001_dis(uint16_t op); /**< fmov.s @Rm+,FRn */
void __1111nnnnmmmm1010_dis(uint16_t op); /**< fmov.s FRm,@Rn */
void __1111nnnnmmmm1011_dis(uint16_t op); /**< fmov.s FRm,@-Rn */
void __1111nnnnmmmm0111_dis(uint16_t op); /**< fmov.s FRm,@(R0,Rn) */
void __1111nnn0mmm01100_dis(uint16_t op); /**< fmov DRm,DRn */
void __1111nnn0mmmm1000_dis(uint16_t op); /**< fmov @Rm,DRn */
void __1111nnn0mmmm0110_dis(uint16_t op); /**< fmov @(R0,Rm),DRn */
void __1111nnn0mmmm1001_dis(uint16_t op); /**< fmov @Rm+,DRn */
void __1111nnnnmmm01010_dis(uint16_t op); /**< fmov DRm,@Rn */
void __1111nnnnmmm01011_dis(uint16_t op); /**< fmov DRm,@-Rn */
void __1111nnnnmmm00111_dis(uint16_t op); /**< fmov DRm,@(R0,Rn) */
void __1111mmmm00011101_dis(uint16_t op); /**< flds FRm,FPUL */
void __1111nnnn00001101_dis(uint16_t op); /**< fsts FPUL,FRn */
void __1111nnnn01011101_dis(uint16_t op); /**< fabs FRn */
void __1111nnnnmmmm0000_dis(uint16_t op); /**< fadd FRm,FRn */
void __1111nnnnmmmm0100_dis(uint16_t op); /**< fcmp/eq FRm,FRn */
void __1111nnnnmmmm0101_dis(uint16_t op); /**< fcmp/gt FRm,FRn */
void __1111nnnnmmmm0011_dis(uint16_t op); /**< fdiv FRm,FRn */
void __1111nnnn00101101_dis(uint16_t op); /**< float FPUL,FRn */
void __1111nnnnmmmm1110_dis(uint16_t op); /**< fmac FR0,FRm,FRn */
void __1111nnnnmmmm0010_dis(uint16_t op); /**< fmul FRm,FRn */
void __1111nnnn01001101_dis(uint16_t op); /**< fneg FRn */
void __1111nnnn01101101_dis(uint16_t op); /**< fsqrt FRn */
void __1111nnnnmmmm0001_dis(uint16_t op); /**< fsub FRm,FRn */
void __1111mmmm00111101_dis(uint16_t op); /**< ftrc FRm,FPUL */
void __1111nnn001011101_dis(uint16_t op); /**< fabs DRn */
void __1111nnn0mmm00000_dis(uint16_t op); /**< fadd DRm,DRn */
void __1111nnn0mmm00100_dis(uint16_t op); /**< fcmp/eq DRm,DRn */
void __1111nnn0mmm00101_dis(uint16_t op); /**< fcmp/gt DRm,DRn */
void __1111nnn0mmm00011_dis(uint16_t op); /**< fdiv DRm,DRn */
void __1111mmm010111101_dis(uint16_t op); /**< fcnvds DRm,FPUL */
void __1111nnn010101101_dis(uint16_t op); /**< fcnvsd FPUL,DRn */
void __1111nnn000101101_dis(uint16_t op); /**< float FPUL,DRn */
void __1111nnn0mmm00010_dis(uint16_t op); /**< fmul DRm,DRn */
void __1111nnn001001101_dis(uint16_t op); /**< fneg DRn */
void __1111nnn001101101_dis(uint16_t op); /**< fsqrt DRn */
void __1111nnn0mmm00001_dis(uint16_t op); /**< fsub DRm,DRn */
void __1111mmm000111101_dis(uint16_t op); /**< ftrc DRm,FPUL */
void __0100mmmm01101010_dis(uint16_t op); /**< lds Rm,FPSCR */
void __0100mmmm01011010_dis(uint16_t op); /**< lds Rm,FPUL */
void __0100mmmm01100110_dis(uint16_t op); /**< lds.l @Rm+,FPSCR */
void __0100mmmm01010110_dis(uint16_t op); /**< lds.l @Rm+,FPUL */
void __0000nnnn01101010_dis(uint16_t op); /**< sts FPSCR,Rn */
void __0000nnnn01011010_dis(uint16_t op); /**< sts FPUL,Rn */
void __0100nnnn01100010_dis(uint16_t op); /**< sts.l FPSCR,@-Rn */
void __0100nnnn01010010_dis(uint16_t op); /**< sts.l FPUL,@-Rn */
void __1111nnn1mmm01100_dis(uint16_t op); /**< fmov DRm,XDn */
void __1111nnn0mmm11100_dis(uint16_t op); /**< fmov XDm,DRn */
void __1111nnn1mmm11100_dis(uint16_t op); /**< fmov XDm,XDn */
void __1111nnn1mmmm1000_dis(uint16_t op); /**< fmov @Rm,XDn */
void __1111nnn1mmmm1001_dis(uint16_t op); /**< fmov @Rm+,XDn */
void __1111nnn1mmmm0110_dis(uint16_t op); /**< fmov @(R0,Rm),DRn */
void __1111nnnnmmm11010_dis(uint16_t op); /**< fmov XDm,@Rn */
void __1111nnnnmmm11011_dis(uint16_t op); /**< fmov XDm,@-Rn */
void __1111nnnnmmm10111_dis(uint16_t op); /**< fmov XDm,@(R0,Rn) */
void __1111nnmm11101101_dis(uint16_t op); /**< fipr FVm,FVn */
void __1111nn0111111101_dis(uint16_t op); /**< ftrv XMTRX,FVn */
void __1111101111111101_dis(uint16_t op); /**< frchg */
void __1111001111111101_dis(uint16_t op); /**< fschg */

/* Opcodes disassembler lookup table declaration */
extern SH4OPProcesor_t SH7750DisasmLUT[];

#endif // SH7750_ENABLE_DISASSEMBLER

#endif // __SH4OPCODE_H__
